using System.Text;

namespace RobloxTypeGenerator.Generators;

/// <summary>
/// Generates Lua type stubs for Roblox Instance classes.
/// These stubs enable Instance types to be used as generic type parameters
/// (e.g., Dictionary&lt;string, TextButton&gt;) at Lua runtime.
/// </summary>
public class LuaTypeStubGenerator
{
    private readonly List<ApiClass> _classes;

    public LuaTypeStubGenerator(List<ApiClass> classes)
    {
        _classes = classes;
    }

    public string Generate()
    {
        var sb = new StringBuilder();

        // Header
        sb.AppendLine("-- Auto-generated Roblox Instance type stubs");
        sb.AppendLine("-- Generated by RobloxTypeGenerator");
        sb.AppendLine("-- These enable Instance types in generic type parameters (Dictionary, List, etc.)");
        sb.AppendLine($"-- Class count: {_classes.Count}");
        sb.AppendLine();

        // Module function
        sb.AppendLine("return function(namespace)");
        sb.AppendLine("  local Roblox = _G[namespace].Roblox");
        sb.AppendLine();

        // Stub helper function
        sb.AppendLine("  -- Type stub for generic type parameters");
        sb.AppendLine("  local function stub(name)");
        sb.AppendLine("    return {");
        sb.AppendLine("      __name__ = name,");
        sb.AppendLine("      default = function() return nil end,");
        sb.AppendLine("      __clone__ = function(v) return v end");
        sb.AppendLine("    }");
        sb.AppendLine("  end");
        sb.AppendLine();

        // Generate stubs for all classes, sorted alphabetically
        sb.AppendLine("  -- Instance type stubs");
        foreach (var cls in _classes.OrderBy(c => c.Name))
        {
            sb.AppendLine($"  Roblox.{cls.Name} = stub(\"{cls.Name}\")");
        }

        sb.AppendLine();
        sb.AppendLine("  return Roblox");
        sb.AppendLine("end");

        return sb.ToString();
    }
}
