-- Generated by CSharp.lua Compiler
local System = _G.MyGame.System
local ListString = System.List(System.String)
local GameSystem
System.import(function (out)
  GameSystem = out.GameSystem
end)
System.namespace("GameSystem", function (namespace)

  -- <summary>
  -- Factory for creating pre-configured character entities
  -- </summary>
  namespace.class("CharacterFactory", function (namespace)
    local CreateCharacter, SetBaseStats, GiveStartingItems
    CreateCharacter = function (name, characterClass, level)
      local entity = GameSystem.Entity(name)

      -- Add stats component
      local stats = GameSystem.StatsComponent()
      entity:AddComponent(stats)

      -- Set base stats based on class
      SetBaseStats(stats, characterClass, level)

      -- Add inventory
      local inventory = GameSystem.InventoryComponent(20)
      entity:AddComponent(inventory)

      -- Add combat component
      local combat = GameSystem.CombatComponent(entity)
      entity:AddComponent(combat)

      -- Give starting items
      GiveStartingItems(inventory, characterClass)

      return entity
    end
    SetBaseStats = function (stats, characterClass, level)
      -- Base stats that scale with level
      local healthBase, manaBase, attackBase, defenseBase

      repeat
        if characterClass == 0 --[[CharacterClass.Warrior]] then
          healthBase = 150
          manaBase = 30
          attackBase = 15
          defenseBase = 12
          break
        elseif characterClass == 1 --[[CharacterClass.Mage]] then
          healthBase = 80
          manaBase = 150
          attackBase = 8
          defenseBase = 5
          break
        elseif characterClass == 2 --[[CharacterClass.Rogue]] then
          healthBase = 100
          manaBase = 50
          attackBase = 12
          defenseBase = 7
          break
        elseif characterClass == 3 --[[CharacterClass.Paladin]] then
          healthBase = 120
          manaBase = 80
          attackBase = 10
          defenseBase = 15
          break
        else
          healthBase = 100
          manaBase = 50
          attackBase = 10
          defenseBase = 10
          break
        end
      until 1

      -- Scale with level
      local levelMultiplier = 1 + (level - 1) * 0.1

      stats:GetOrCreateStat("Health", healthBase * levelMultiplier)
      stats:GetOrCreateStat("MaxHealth", healthBase * levelMultiplier)
      stats:GetOrCreateStat("Mana", manaBase * levelMultiplier)
      stats:GetOrCreateStat("MaxMana", manaBase * levelMultiplier)
      stats:GetOrCreateStat("AttackPower", attackBase * levelMultiplier)
      stats:GetOrCreateStat("Defense", defenseBase * levelMultiplier)
      stats:GetOrCreateStat("CritChance", (characterClass == 2 --[[CharacterClass.Rogue]]) and 15 or 5)
      stats:GetOrCreateStat("CritMultiplier", 150)
      stats:GetOrCreateStat("DodgeChance", (characterClass == 2 --[[CharacterClass.Rogue]]) and 10 or 3)
      stats:GetOrCreateStat("Level", level)
    end
    GiveStartingItems = function (inventory, characterClass)
      -- Give a health potion to everyone
      local default = GameSystem.Item("Health Potion", "Restores 50 health", 0 --[[ItemRarity.Common]], 10)
      default.StackSize = 3
      local healthPotion = default
      inventory:AddItem(healthPotion)

      -- Class-specific starting weapon
      local weapon
      repeat
        if characterClass == 0 --[[CharacterClass.Warrior]] then
          weapon = GameSystem.Item("Iron Sword", "A sturdy iron sword", 0 --[[ItemRarity.Common]], 1):WithStatBonus("AttackPower", 5)
          break
        elseif characterClass == 1 --[[CharacterClass.Mage]] then
          weapon = GameSystem.Item("Apprentice Staff", "A basic magic staff", 0 --[[ItemRarity.Common]], 1):WithStatBonus("AttackPower", 3):WithStatBonus("MaxMana", 20)
          break
        elseif characterClass == 2 --[[CharacterClass.Rogue]] then
          weapon = GameSystem.Item("Steel Dagger", "A sharp dagger", 0 --[[ItemRarity.Common]], 1):WithStatBonus("AttackPower", 4):WithStatBonus("CritChance", 5)
          break
        elseif characterClass == 3 --[[CharacterClass.Paladin]] then
          weapon = GameSystem.Item("Blessed Mace", "A holy weapon", 1 --[[ItemRarity.Uncommon]], 1):WithStatBonus("AttackPower", 4):WithStatBonus("Defense", 3)
          break
        else
          weapon = GameSystem.Item("Wooden Stick", "Better than nothing", 0 --[[ItemRarity.Common]], 1):WithStatBonus("AttackPower", 1)
          break
        end
      until 1
      inventory:AddItem(weapon)
    end
    return {
      CreateCharacter = CreateCharacter
    }
  end)

  -- <summary>
  -- Extension methods for working with character entities
  -- </summary>
  namespace.class("CharacterExtensions", function (namespace)
    local IsAlive, GetHealthPercent, Heal, GetStatusReport
    IsAlive = function (entity)
      local stats = entity:GetComponent(GameSystem.StatsComponent)
      if stats == nil then
        return entity.IsActive
      end

      return stats:GetStatValue("Health") > 0
    end
    GetHealthPercent = function (entity)
      local stats = entity:GetComponent(GameSystem.StatsComponent)
      if stats == nil then
        return 100
      end

      local health = stats:GetStatValue("Health")
      local maxHealth = stats:GetStatValue("MaxHealth")
      if maxHealth == 0 then
        return 100
      end

      return (health / maxHealth) * 100
    end
    Heal = function (entity, amount)
      local stats = entity:GetComponent(GameSystem.StatsComponent)
      if stats == nil then
        return
      end

      local healthStat = stats:GetStat("Health")
      local maxHealthStat = stats:GetStat("MaxHealth")
      if healthStat == nil or maxHealthStat == nil then
        return
      end

      healthStat.BaseValue = math.min(healthStat.BaseValue + amount, maxHealthStat:getValue())
    end
    GetStatusReport = function (entity)
      local stats = entity:GetComponent(GameSystem.StatsComponent)
      local inventory = entity:GetComponent(GameSystem.InventoryComponent)

      local default = ListString()
      default:Add("=== " .. entity.Name .. " ===")
      default:Add("Active: " .. entity.IsActive)
      local lines = default

      if stats ~= nil then
        lines:Add("Health: " .. System.toString(stats:GetStatValue("Health"), "F0") .. "/" .. System.toString(stats:GetStatValue("MaxHealth"), "F0"))
        lines:Add("Mana: " .. System.toString(stats:GetStatValue("Mana"), "F0") .. "/" .. System.toString(stats:GetStatValue("MaxMana"), "F0"))
        lines:Add("Attack: " .. System.toString(stats:GetStatValue("AttackPower"), "F1"))
        lines:Add("Defense: " .. System.toString(stats:GetStatValue("Defense"), "F1"))
        lines:Add("Crit: " .. System.toString(stats:GetStatValue("CritChance"), "F0") .. "%")
      end

      if inventory ~= nil then
        lines:Add("Inventory: " .. inventory:getUsedSlots() .. "/" .. inventory.Capacity)
        for _, item in System.each(inventory:GetAllItems()) do
          lines:Add("  - " .. System.toString(item))
        end
      end

      return System.String.JoinEnumerable("\n", lines)
    end
    return {
      IsAlive = IsAlive,
      GetHealthPercent = GetHealthPercent,
      Heal = Heal,
      GetStatusReport = GetStatusReport
    }
  end)
end)

return true
