-- Generated by CSharp.lua Compiler
local System = _G.MyGame.System
local Linq = System.Linq.Enumerable
local GameSystem
local ListIComponent
System.import(function (out)
  GameSystem = out.GameSystem
  ListIComponent = System.List(GameSystem.IComponent)
end)
System.namespace("GameSystem", function (namespace)
  -- <summary>
  -- Base interface for all game components
  -- </summary>
  namespace.interface("IComponent", function ()
    return {}
  end)

  -- <summary>
  -- Base entity class that can hold components
  -- </summary>
  namespace.class("Entity", function (namespace)
    local _nextId, AddComponent, GetComponent, GetComponents, HasComponent, Update, ToString, __ctor__
    __ctor__ = function (this, name)
      this._components = ListIComponent()
      local default = _nextId
      _nextId = default + 1
      this.Id = default
      this.Name = name
    end
    _nextId = 1
    AddComponent = function (this, component)
      this._components:Add(component)
    end
    GetComponent = function (this, T)
      return Linq.FirstOrDefault(Linq.OfType(this._components, T))
    end
    GetComponents = function (this, T)
      return Linq.OfType(this._components, T)
    end
    HasComponent = function (this, T)
      return Linq.Any(this._components, function (c)
        return System.is(c, T)
      end)
    end
    Update = function (this, deltaTime)
      if not this.IsActive then
        return
      end

      for _, component in System.each(this._components) do
        component:Update(deltaTime)
      end
    end
    ToString = function (this)
      return "Entity[" .. this.Id .. "]: " .. this.Name .. " (" .. #this._components .. " components)"
    end
    return {
      Id = 0,
      IsActive = true,
      AddComponent = AddComponent,
      GetComponent = GetComponent,
      GetComponents = GetComponents,
      HasComponent = HasComponent,
      Update = Update,
      ToString = ToString,
      __ctor__ = __ctor__
    }
  end)
end)

return true
