-- Generated by CSharp.lua Compiler
local System = _G.MyGame.System
local Linq = System.Linq.Enumerable
local ListInt32 = System.List(System.Int32)
local ListString = System.List(System.String)
local DictStringListInt32 = System.Dictionary(System.String, ListInt32)
local GameSystem
local GameSystemTestResults
local ListEntity
local ListTestResult
System.import(function (out)
  GameSystem = out.GameSystem
  GameSystemTestResults = GameSystem.TestResults
  ListEntity = System.List(GameSystem.Entity)
  ListTestResult = System.List(GameSystemTestResults.TestResult)
end)
System.namespace("GameSystem", function (namespace)
  -- <summary>
  -- Manages the game state and provides the main test interface
  -- </summary>
  namespace.class("GameManager", function (namespace)
    local Log, AddEntity, GetEntity, GetActiveEntities, Update, RunAllTests, TestEntityCreation, TestStatsSystem, 
    TestInventorySystem, TestCombatSystem, TestCharacterFactory, TestLinqQueries, TestEventsAndDelegates, TestGenerics, TestBattleSimulation, __ctor__
    __ctor__ = function (this)
      this._entities = ListEntity()
      this._random = System.Random()
    end
    Log = function (this, message)
      local default = this.OnLog
      if default ~= nil then
        default(message)
      end
    end
    AddEntity = function (this, entity)
      this._entities:Add(entity)
      Log(this, "Added entity: " .. System.toString(entity))
    end
    GetEntity = function (this, name)
      return Linq.FirstOrDefault(this._entities, function (e)
        return e.Name == name
      end)
    end
    GetActiveEntities = function (this)
      return Linq.Where(this._entities, function (e)
        return e.IsActive
      end)
    end
    Update = function (this, deltaTime)
      for _, entity in System.each(GetActiveEntities(this)) do
        entity:Update(deltaTime)
      end
    end
    -- <summary>
    -- Run a comprehensive test of all game systems
    -- </summary>
    RunAllTests = function (this)
      local results = GameSystem.TestResults()

      -- Test 1: Entity creation
      results:AddTest("Entity Creation", System.fn(this, TestEntityCreation))

      -- Test 2: Stats system
      results:AddTest("Stats System", System.fn(this, TestStatsSystem))

      -- Test 3: Inventory system
      results:AddTest("Inventory System", System.fn(this, TestInventorySystem))

      -- Test 4: Combat system
      results:AddTest("Combat System", System.fn(this, TestCombatSystem))

      -- Test 5: Character factory
      results:AddTest("Character Factory", System.fn(this, TestCharacterFactory))

      -- Test 6: LINQ queries
      results:AddTest("LINQ Queries", System.fn(this, TestLinqQueries))

      -- Test 7: Events and delegates
      results:AddTest("Events and Delegates", System.fn(this, TestEventsAndDelegates))

      -- Test 8: Generics
      results:AddTest("Generics", System.fn(this, TestGenerics))

      -- Test 9: Full battle simulation
      results:AddTest("Battle Simulation", System.fn(this, TestBattleSimulation))

      return results
    end
    TestEntityCreation = function (this)
      local entity = GameSystem.Entity("TestEntity")
      if entity.Id <= 0 then
        return false
      end
      if entity.Name ~= "TestEntity" then
        return false
      end
      if not entity.IsActive then
        return false
      end

      entity:AddComponent(GameSystem.StatsComponent())
      if not entity:HasComponent(GameSystem.StatsComponent) then
        return false
      end
      if entity:GetComponent(GameSystem.StatsComponent) == nil then
        return false
      end

      Log(this, "Entity creation: All checks passed")
      return true
    end
    TestStatsSystem = function (this)
      local stats = GameSystem.StatsComponent()

      local health = stats:GetOrCreateStat("Health", 100)
      if health:getValue() ~= 100 then
        return false
      end

      -- Test flat modifier
      local flatMod = GameSystem.StatModifier("Test", 0 --[[ModifierType.Flat]], 20)
      health:AddModifier(flatMod)
      if math.abs(health:getValue() - 120) > 0.01 then
        return false
      end

      -- Test percent modifier
      local percentMod = GameSystem.StatModifier("Test", 1 --[[ModifierType.Percent]], 50)
      health:AddModifier(percentMod)
      -- (100 + 20) * 1.5 = 180
      if math.abs(health:getValue() - 180) > 0.01 then
        return false
      end

      -- Test remove modifier
      health:RemoveModifier(flatMod)
      -- 100 * 1.5 = 150
      if math.abs(health:getValue() - 150) > 0.01 then
        return false
      end

      Log(this, "Stats system: All checks passed")
      return true
    end
    TestInventorySystem = function (this)
      local inventory = GameSystem.InventoryComponent(5)

      -- Test adding items
      local sword = GameSystem.Item("Sword", "A sword", 0 --[[ItemRarity.Common]], 1)
      if not inventory:AddItem(sword) then
        return false
      end
      if inventory:getUsedSlots() ~= 1 then
        return false
      end

      -- Test stacking
      local default = GameSystem.Item("Potion", "Heals", 0 --[[ItemRarity.Common]], 10)
      default.StackSize = 3
      local potion1 = default
      local default = GameSystem.Item("Potion", "Heals", 0 --[[ItemRarity.Common]], 10)
      default.StackSize = 2
      local potion2 = default
      inventory:AddItem(potion1)
      inventory:AddItem(potion2)
      if inventory:CountItem("Potion") ~= 5 then
        return false
      end

      -- Test has item
      if not inventory:HasItem("Sword", 1) then
        return false
      end
      if not inventory:HasItem("Potion", 5) then
        return false
      end
      if inventory:HasItem("Potion", 10) then
        return false
      end

      -- Test remove item
      local removed = inventory:RemoveItem("Potion", 2)
      if removed == nil or removed.StackSize ~= 2 then
        return false
      end
      if inventory:CountItem("Potion") ~= 3 then
        return false
      end

      -- Test rarity filter
      local rare = GameSystem.Item("Rare Item", "Rare", 2 --[[ItemRarity.Rare]], 1)
      inventory:AddItem(rare)
      local rareItems = Linq.ToList(inventory:GetItemsByRarity(2 --[[ItemRarity.Rare]]))
      if #rareItems ~= 1 then
        return false
      end

      Log(this, "Inventory system: All checks passed")
      return true
    end
    TestCombatSystem = function (this)
      local attacker = GameSystem.CharacterFactory.CreateCharacter("Attacker", 0 --[[CharacterClass.Warrior]], 5)
      local defender = GameSystem.CharacterFactory.CreateCharacter("Defender", 3 --[[CharacterClass.Paladin]], 5)

      local attackerCombat = attacker:GetComponent(GameSystem.CombatComponent)
      local defenderStats = defender:GetComponent(GameSystem.StatsComponent)

      local healthBefore = defenderStats:GetStatValue("Health")
      attackerCombat:Attack(defender, 20, 0 --[[DamageType.Physical]])
      local healthAfter = defenderStats:GetStatValue("Health")

      -- Damage should have been dealt (unless dodged, but we can't control RNG)
      -- Just verify the system runs without errors
      Log(this, "Combat: Health went from " .. System.toString(healthBefore, "F0") .. " to " .. System.toString(healthAfter, "F0"))

      return true
    end
    TestCharacterFactory = function (this)
      local warrior = GameSystem.CharacterFactory.CreateCharacter("TestWarrior", 0 --[[CharacterClass.Warrior]], 10)
      local mage = GameSystem.CharacterFactory.CreateCharacter("TestMage", 1 --[[CharacterClass.Mage]], 10)

      local warriorStats = warrior:GetComponent(GameSystem.StatsComponent)
      local mageStats = mage:GetComponent(GameSystem.StatsComponent)

      -- Warrior should have more health than mage
      if warriorStats:GetStatValue("MaxHealth") <= mageStats:GetStatValue("MaxHealth") then
        return false
      end

      -- Mage should have more mana
      if mageStats:GetStatValue("MaxMana") <= warriorStats:GetStatValue("MaxMana") then
        return false
      end

      -- Both should have inventory with items
      local warriorInv = warrior:GetComponent(GameSystem.InventoryComponent)
      local mageInv = mage:GetComponent(GameSystem.InventoryComponent)

      if warriorInv:getUsedSlots() < 2 then
        return false
      end
      if mageInv:getUsedSlots() < 2 then
        return false
      end

      Log(this, "Character factory: All checks passed")
      return true
    end
    TestLinqQueries = function (this)
      -- Clear and add test entities
      this._entities:Clear()

      for i = 1, 5 do
        local entity = GameSystem.CharacterFactory.CreateCharacter("Hero" .. i, 0 --[[CharacterClass.Warrior]], i * 2)
        this._entities:Add(entity)
      end

      -- Test various LINQ operations
      local count = Linq.Count(this._entities)
      if count ~= 5 then
        return false
      end

      local first = Linq.First(this._entities)
      if first.Name ~= "Hero1" then
        return false
      end

      local last = Linq.Last(this._entities)
      if last.Name ~= "Hero5" then
        return false
      end

      local filtered = Linq.ToList(Linq.Where(this._entities, function (e)
        return System.String.Contains(e.Name, "3")
      end))
      if #filtered ~= 1 then
        return false
      end

      local ordered = Linq.ToList(Linq.OrderByDescending(this._entities, function (e)
        return e:GetComponent(GameSystem.StatsComponent):GetStatValue("MaxHealth")
      end, nil, System.Single))
      if Linq.First(ordered).Name ~= "Hero5" then
        return false
      end

      local names = Linq.ToList(Linq.Select(this._entities, function (e)
        return e.Name
      end, System.String))
      if #names ~= 5 then
        return false
      end

      local any = Linq.Any(this._entities, function (e)
        return e.Name == "Hero3"
      end)
      if not any then
        return false
      end

      local all = Linq.All(this._entities, function (e)
        return e.IsActive
      end)
      if not all then
        return false
      end

      Log(this, "LINQ queries: All checks passed")
      return true
    end
    TestEventsAndDelegates = function (this)
      local entity = GameSystem.CharacterFactory.CreateCharacter("EventTest", 2 --[[CharacterClass.Rogue]], 1)
      local inventory = entity:GetComponent(GameSystem.InventoryComponent)

      local addedCount = 0
      local removedCount = 0

      inventory.OnItemAdded = System.DelegateCombine(inventory.OnItemAdded, function (item)
        addedCount = addedCount + 1
      end)
      inventory.OnItemRemoved = System.DelegateCombine(inventory.OnItemRemoved, function (item)
        removedCount = removedCount + 1
      end)

      local item1 = GameSystem.Item("TestItem1", "Test", 0 --[[ItemRarity.Common]], 1)
      local item2 = GameSystem.Item("TestItem2", "Test", 1 --[[ItemRarity.Uncommon]], 1)

      inventory:AddItem(item1)
      inventory:AddItem(item2)

      if addedCount ~= 2 then
        return false
      end

      inventory:RemoveItem("TestItem1", 1)

      if removedCount ~= 1 then
        return false
      end

      Log(this, "Events and delegates: All checks passed")
      return true
    end
    TestGenerics = function (this)
      local entity = GameSystem.Entity("GenericTest")
      entity:AddComponent(GameSystem.StatsComponent())
      entity:AddComponent(GameSystem.InventoryComponent(10))
      entity:AddComponent(GameSystem.CombatComponent(entity))

      -- Test generic GetComponent
      local stats = entity:GetComponent(GameSystem.StatsComponent)
      local inv = entity:GetComponent(GameSystem.InventoryComponent)
      local combat = entity:GetComponent(GameSystem.CombatComponent)

      if stats == nil or inv == nil or combat == nil then
        return false
      end

      -- Test generic HasComponent
      if not entity:HasComponent(GameSystem.StatsComponent) then
        return false
      end
      if not entity:HasComponent(GameSystem.InventoryComponent) then
        return false
      end

      -- Test GetComponents (multiple)
      local allComponents = Linq.ToList(entity:GetComponents(GameSystem.IComponent))
      if #allComponents ~= 3 then
        return false
      end

      -- Test generic collections
      local dict = DictStringListInt32()
      local default = ListInt32()
      default:Add(1)
      default:Add(2)
      default:Add(3)
      dict:set("test", default)
      if Linq.Sum(dict:get("test")) ~= 6 then
        return false
      end

      Log(this, "Generics: All checks passed")
      return true
    end
    TestBattleSimulation = function (this)
      Log(this, "=== Starting Battle Simulation ===")

      local hero = GameSystem.CharacterFactory.CreateCharacter("Hero", 3 --[[CharacterClass.Paladin]], 10)
      local enemy = GameSystem.CharacterFactory.CreateCharacter("Goblin", 2 --[[CharacterClass.Rogue]], 8)

      local heroCombat = hero:GetComponent(GameSystem.CombatComponent)
      local enemyCombat = enemy:GetComponent(GameSystem.CombatComponent)

      heroCombat.OnDamageDealt = System.DelegateCombine(heroCombat.OnDamageDealt, function (target, result)
        Log(this, hero.Name .. " dealt " .. System.toString(result) .. " to " .. target.Name)
      end)

      enemyCombat.OnDamageDealt = System.DelegateCombine(enemyCombat.OnDamageDealt, function (target, result)
        Log(this, enemy.Name .. " dealt " .. System.toString(result) .. " to " .. target.Name)
      end)

      heroCombat.OnDeath = System.DelegateCombine(heroCombat.OnDeath, function ()
        Log(this, hero.Name .. " has fallen!")
      end)
      enemyCombat.OnDeath = System.DelegateCombine(enemyCombat.OnDeath, function ()
        Log(this, enemy.Name .. " has been defeated!")
      end)

      local round = 0
      while GameSystem.CharacterExtensions.IsAlive(hero) and GameSystem.CharacterExtensions.IsAlive(enemy) and round < 20 do
        round = round + 1
        Log(this, "--- Round " .. round .. " ---")
        Log(this, hero.Name .. ": " .. System.toString(GameSystem.CharacterExtensions.GetHealthPercent(hero), "F0") .. "% HP")
        Log(this, enemy.Name .. ": " .. System.toString(GameSystem.CharacterExtensions.GetHealthPercent(enemy), "F0") .. "% HP")

        -- Hero attacks
        if GameSystem.CharacterExtensions.IsAlive(hero) then
          heroCombat:Attack(enemy, 15 + this._random:Next(10), 0 --[[DamageType.Physical]])
        end

        -- Enemy attacks
        if GameSystem.CharacterExtensions.IsAlive(enemy) then
          enemyCombat:Attack(hero, 10 + this._random:Next(8), 0 --[[DamageType.Physical]])
        end
      end

      Log(this, "=== Battle Complete ===")
      local default
      if GameSystem.CharacterExtensions.IsAlive(hero) then
        default = hero.Name .. " wins!"
      else
        default = enemy.Name .. " wins!"
      end
      Log(this, default)

      return true
    end
    return {
      Log = Log,
      AddEntity = AddEntity,
      GetEntity = GetEntity,
      GetActiveEntities = GetActiveEntities,
      Update = Update,
      RunAllTests = RunAllTests,
      __ctor__ = __ctor__
    }
  end)

  namespace.class("TestResults", function (namespace)
    local AddTest, getTotalTests, getPassedTests, getFailedTests, GetAllResults, GetFailedResults, ToString, class, 
    __ctor__
    namespace.class("TestResult", function (namespace)
      return {
        Passed = false
      }
    end)
    __ctor__ = function (this)
      this._results = ListTestResult()
    end
    AddTest = function (this, name, test)
      local default = class.TestResult()
      default.Name = name
      local result = default
      System.try(function ()
        result.Passed = test()
      end, function (default)
        local ex = default
        result.Passed = false
        result.Error = ex:getMessage()
      end)
      this._results:Add(result)
    end
    getTotalTests = function (this)
      return #this._results
    end
    getPassedTests = function (this)
      return Linq.Count(this._results, function (r)
        return r.Passed
      end)
    end
    getFailedTests = function (this)
      return Linq.Count(this._results, function (r)
        return not r.Passed
      end)
    end
    GetAllResults = function (this)
      return this._results
    end
    GetFailedResults = function (this)
      return Linq.Where(this._results, function (r)
        return not r.Passed
      end)
    end
    ToString = function (this)
      local default = ListString()
      default:Add("========== TEST RESULTS ==========")
      default:Add("Total: " .. getTotalTests(this) .. ", Passed: " .. getPassedTests(this) .. ", Failed: " .. getFailedTests(this))
      default:Add("")
      local lines = default

      for _, result in System.each(this._results) do
        local status = result.Passed and "[PASS]" or "[FAIL]"
        lines:Add(status .. " " .. result.Name)
        if not result.Passed and not System.String.IsNullOrEmpty(result.Error) then
          lines:Add("       Error: " .. result.Error)
        end
      end

      lines:Add("")
      lines:Add((getFailedTests(this) == 0) and "All tests passed!" or (getFailedTests(this) .. " test(s) failed."))
      lines:Add("==================================")

      return System.String.JoinEnumerable("\n", lines)
    end
    class = {
      AddTest = AddTest,
      getTotalTests = getTotalTests,
      getPassedTests = getPassedTests,
      getFailedTests = getFailedTests,
      GetAllResults = GetAllResults,
      GetFailedResults = GetFailedResults,
      ToString = ToString,
      __ctor__ = __ctor__
    }
    return class
  end)
end)

return true
