-- Generated by CSharp.lua Compiler
local System = _G.MyGame.System
local Linq = System.Linq.Enumerable
local DictStringSingle = System.Dictionary(System.String, System.Single)
local GameSystem
local ListInventorySlot
System.import(function (out)
  GameSystem = out.GameSystem
  ListInventorySlot = System.List(GameSystem.InventorySlot)
end)
System.namespace("GameSystem", function (namespace)
  namespace.enum("ItemRarity", function ()
    local __ctor__
    __ctor__ = function (this)
      System.base(this).__ctor__(this)
    end
    return {
      Common = 0,
      Uncommon = 1,
      Rare = 2,
      Epic = 3,
      Legendary = 4,
      __ctor__ = __ctor__
    }
  end)

  namespace.class("Item", function (namespace)
    local _nextId, WithStatBonus, getCanStack, ToString, __ctor__
    __ctor__ = function (this, name, description, rarity, maxStackSize)
      this.StatBonuses = DictStringSingle()
      local default = _nextId
      _nextId = default + 1
      this.Id = default
      this.Name = name
      this.Description = description
      this.Rarity = rarity
      this.MaxStackSize = maxStackSize
    end
    _nextId = 1
    WithStatBonus = function (this, stat, value)
      this.StatBonuses:set(stat, value)
      return this
    end
    getCanStack = function (this)
      return this.MaxStackSize > 1
    end
    ToString = function (this)
      return "[" .. System.EnumToString(this.Rarity, GameSystem.ItemRarity) .. "] " .. this.Name .. " x" .. this.StackSize
    end
    return {
      Id = 0,
      Rarity = 0,
      StackSize = 1,
      MaxStackSize = 0,
      WithStatBonus = WithStatBonus,
      getCanStack = getCanStack,
      ToString = ToString,
      __ctor__ = __ctor__
    }
  end)

  namespace.class("InventorySlot", function (namespace)
    local getIsEmpty, TryAddItem, TakeItem
    getIsEmpty = function (this)
      return this.Item == nil
    end
    TryAddItem = function (this, item, remaining)
      remaining = item.StackSize

      if getIsEmpty(this) then
        this.Item = item
        remaining = 0
        return true, remaining
      end

      if this.Item.Name == item.Name and this.Item:getCanStack() then
        local space = this.Item.MaxStackSize - this.Item.StackSize
        local toAdd = math.min(space, item.StackSize)
        this.Item.StackSize = this.Item.StackSize + toAdd
        remaining = item.StackSize - toAdd
        return remaining == 0, remaining
      end

      return false, remaining
    end
    TakeItem = function (this, count)
      if getIsEmpty(this) then
        return nil
      end

      if count >= this.Item.StackSize then
        local item = this.Item
        this.Item = nil
        return item
      end

      this.Item.StackSize = this.Item.StackSize - count
      local default = GameSystem.Item(this.Item.Name, this.Item.Description, this.Item.Rarity, this.Item.MaxStackSize)
      default.StackSize = count
      return default
    end
    return {
      getIsEmpty = getIsEmpty,
      TryAddItem = TryAddItem,
      TakeItem = TakeItem
    }
  end)

  namespace.class("InventoryComponent", function (namespace)
    local getName, AddItem, RemoveItem, GetAllItems, GetItemsByRarity, CountItem, HasItem, getUsedSlots, 
    getFreeSlots, Update, __ctor__
    __ctor__ = function (this, capacity)
      this.Capacity = capacity
      this._slots = ListInventorySlot()
      for i = 0, capacity - 1 do
        this._slots:Add(GameSystem.InventorySlot())
      end
    end
    getName = function (this)
      return "Inventory"
    end
    AddItem = function (this, item)
      -- First try to stack with existing items
      for _, slot in System.each(Linq.Where(this._slots, function (s)
        return not s:getIsEmpty() and s.Item.Name == item.Name and s.Item:getCanStack()
      end)) do
        local default, remaining = slot:TryAddItem(item)
        if default then
          local extern = this.OnItemAdded
          if extern ~= nil then
            extern(item)
          end
          return true
        end
        if remaining == 0 then
          break
        end
      end

      -- Then try empty slots
      for _, slot in System.each(Linq.Where(this._slots, function (s)
        return s:getIsEmpty()
      end)) do
        local default, _ = slot:TryAddItem(item)
        if default then
          local extern = this.OnItemAdded
          if extern ~= nil then
            extern(item)
          end
          return true
        end
      end

      return false
    end
    RemoveItem = function (this, itemName, count)
      local slot = Linq.FirstOrDefault(this._slots, function (s)
        return not s:getIsEmpty() and s.Item.Name == itemName
      end)
      if slot == nil then
        return nil
      end

      local item = slot:TakeItem(count)
      if item ~= nil then
        local default = this.OnItemRemoved
        if default ~= nil then
          default(item)
        end
      end
      return item
    end
    GetAllItems = function (this)
      return Linq.Select(Linq.Where(this._slots, function (s)
        return not s:getIsEmpty()
      end), function (s)
        return s.Item
      end, GameSystem.Item)
    end
    GetItemsByRarity = function (this, rarity)
      return Linq.Where(GetAllItems(this), function (i)
        return i.Rarity == rarity
      end)
    end
    CountItem = function (this, itemName)
      return Linq.Sum(Linq.Where(this._slots, function (s)
        return not s:getIsEmpty() and s.Item.Name == itemName
      end), function (s)
        return s.Item.StackSize
      end)
    end
    HasItem = function (this, itemName, count)
      return CountItem(this, itemName) >= count
    end
    getUsedSlots = function (this)
      return Linq.Count(this._slots, function (s)
        return not s:getIsEmpty()
      end)
    end
    getFreeSlots = function (this)
      return this.Capacity - getUsedSlots(this)
    end
    Update = function (this, deltaTime)
      -- Inventory doesn't need regular updates
    end
    return {
      base = function (out)
        return {
          out.GameSystem.IComponent
        }
      end,
      getName = getName,
      Capacity = 0,
      AddItem = AddItem,
      RemoveItem = RemoveItem,
      GetAllItems = GetAllItems,
      GetItemsByRarity = GetItemsByRarity,
      CountItem = CountItem,
      HasItem = HasItem,
      getUsedSlots = getUsedSlots,
      getFreeSlots = getFreeSlots,
      Update = Update,
      __ctor__ = __ctor__
    }
  end)
end)

return true
