-- Generated by CSharp.lua Compiler
local System = _G.MyGame.System
return function (path)
  return System.init({
    path = path,
    files = {
      "Character",
      "Combat",
      "Entity",
      "GameManager",
      "Inventory",
      "Stats"
    },
    types = {
      "GameSystem.IComponent",
      "GameSystem.TestResults",
      "GameSystem.CharacterExtensions",
      "GameSystem.CharacterFactory",
      "GameSystem.CombatComponent",
      "GameSystem.DamageResult",
      "GameSystem.DamageType",
      "GameSystem.Entity",
      "GameSystem.GameManager",
      "GameSystem.InventoryComponent",
      "GameSystem.InventorySlot",
      "GameSystem.Item",
      "GameSystem.ItemRarity",
      "GameSystem.Stat",
      "GameSystem.StatModifier",
      "GameSystem.StatsComponent",
      "GameSystem.TestResults.TestResult"
    }
  })
end
