-- Generated by CSharp.lua Compiler
local System = _G.MyGame.System
local Linq = System.Linq.Enumerable
local GameSystem
local DictStringStat
local ListStatModifier
System.import(function (out)
  GameSystem = out.GameSystem
  DictStringStat = System.Dictionary(System.String, GameSystem.Stat)
  ListStatModifier = System.List(GameSystem.StatModifier)
end)
System.namespace("GameSystem", function (namespace)
  -- <summary>
  -- Represents a single stat with base value and modifiers
  -- </summary>
  namespace.class("Stat", function (namespace)
    local getValue, AddModifier, RemoveModifier, ClearModifiers, __ctor__
    __ctor__ = function (this, name, baseValue)
      this._modifiers = ListStatModifier()
      this.Name = name
      this.BaseValue = baseValue
    end
    getValue = function (this)
      local flat = Linq.Sum(Linq.Where(this._modifiers, function (m)
        return m.Type == 0 --[[ModifierType.Flat]]
      end), function (m)
        return m.Value
      end)
      local percent = Linq.Sum(Linq.Where(this._modifiers, function (m)
        return m.Type == 1 --[[ModifierType.Percent]]
      end), function (m)
        return m.Value
      end)
      return (this.BaseValue + flat) * (1 + percent / 100)
    end
    AddModifier = function (this, modifier)
      this._modifiers:Add(modifier)
    end
    RemoveModifier = function (this, modifier)
      this._modifiers:Remove(modifier)
    end
    ClearModifiers = function (this)
      this._modifiers:Clear()
    end
    return {
      BaseValue = 0,
      getValue = getValue,
      AddModifier = AddModifier,
      RemoveModifier = RemoveModifier,
      ClearModifiers = ClearModifiers,
      __ctor__ = __ctor__
    }
  end)


  namespace.class("StatModifier", function (namespace)
    local __ctor__
    __ctor__ = function (this, source, type, value)
      this.Source = source
      this.Type = type
      this.Value = value
    end
    return {
      Type = 0,
      Value = 0,
      __ctor__ = __ctor__
    }
  end)

  -- <summary>
  -- Component that holds multiple stats for an entity
  -- </summary>
  namespace.class("StatsComponent", function (namespace)
    local getName, GetStat, GetOrCreateStat, GetStatValue, getStatNames, Update, __ctor__
    __ctor__ = function (this)
      this._stats = DictStringStat()
    end
    getName = function (this)
      return "Stats"
    end
    GetStat = function (this, name)
      local default, stat = this._stats:TryGetValue(name, nil)
      if default then
        return stat
      end
      return nil
    end
    GetOrCreateStat = function (this, name, defaultValue)
      local default, stat = this._stats:TryGetValue(name, nil)
      if not default then
        stat = GameSystem.Stat(name, defaultValue)
        this._stats:set(name, stat)
      end
      return stat
    end
    GetStatValue = function (this, name)
      local stat = GetStat(this, name)
      local default = stat
      if default ~= nil then
        default = default:getValue()
      end
      return default or 0
    end
    getStatNames = function (this)
      return this._stats:getKeys()
    end
    Update = function (this, deltaTime)
      -- Stats don't need regular updates
    end
    return {
      base = function (out)
        return {
          out.GameSystem.IComponent
        }
      end,
      getName = getName,
      GetStat = GetStat,
      GetOrCreateStat = GetOrCreateStat,
      GetStatValue = GetStatValue,
      getStatNames = getStatNames,
      Update = Update,
      __ctor__ = __ctor__
    }
  end)
end)

return true
