-- Generated by CSharp.lua Compiler
local System = _G.RobloxTest.Runtime.System
return function (path)
  return System.init({
    path = path,
    files = {
      "TestScript"
    },
    types = {
      "RobloxTest.PhysicsTest",
      "RobloxTest.ServerScript",
      "RobloxTest.TestScript"
    },
    Main = "RobloxTest.TestScript.Main",
    assembly = {
      Company = "RobloxTest",
      Configuration = "Debug",
      FileVersion = "1.0.0.0",
      InformationalVersion = "1.0.0+8afcd61a424cbfde5d8ecb8ac341beb85d872027",
      Product = "RobloxTest",
      Title = "RobloxTest",
      Version = "1.0.0.0"
    }
  })
end
