-- Generated by CSharp.lua Compiler
local System = _G.RobloxTest.Runtime.System
local Roblox = Roblox
System.namespace("RobloxTest", function (namespace)
  -- <summary>
  -- Test script demonstrating Roblox API usage from C#.
  -- This should transpile to valid Luau code.
  -- </summary>
  namespace.class("TestScript", function (namespace)
    local Main
    Main = function ()
      -- Test GetService with generic type argument -> should become game:GetService("Players")
      local players = Roblox.Globals.getgame():GetService("Players")

      -- Test event connection with lambda
      players.PlayerAdded:Connect(function (player)
        System.Console.WriteLine("Player joined: " .. player:getName())
        System.Console.WriteLine("UserId: " .. player.UserId)
        System.Console.WriteLine("DisplayName: " .. player.DisplayName)

        -- Test nested event connection
        player.CharacterAdded:Connect(function (character)
          -- Test FindFirstChildOfClass with generic -> should become :FindFirstChildOfClass("Humanoid")
          local humanoid = character:FindFirstChildOfClass("Humanoid")
          if humanoid ~= nil then
            humanoid:TakeDamage(10)
            System.Console.WriteLine("Humanoid health: " .. humanoid.Health)
          end

          -- Test FindFirstChild with string
          local head = character:FindFirstChild("Head")
          if head ~= nil then
            System.Console.WriteLine("Found head!")
          end
        end)
      end)

      -- Test workspace global
      local part = Roblox.Globals.getworkspace():FindFirstChild("TestPart")
      if part ~= nil then
        -- Test IsA with generic -> should become :IsA("BasePart")
        if part:IsA("BasePart") then
          System.Console.WriteLine("TestPart is a BasePart!")
        end
      end

      -- Test Vector3 creation
      local position = Vector3.new(10, 5, 20)
      System.Console.WriteLine("Position: " .. position.X .. ", " .. position.Y .. ", " .. position.Z)

      -- Test Color3 creation
      local color = Color3.fromRGB(255, 128, 64)
      System.Console.WriteLine("Color R: " .. color.R)

      -- Test CFrame creation
      local cframe = CFrame.new(0, 10, 0)
      System.Console.WriteLine("CFrame position: " .. cframe.Position:ToString())
    end
    return {
      Main = Main
    }
  end)

  -- <summary>
  -- Another test class for server-side logic.
  -- </summary>
  namespace.class("ServerScript", function (namespace)
    local Initialize
    Initialize = function ()
      local runService = Roblox.Globals.getgame():GetService("RunService")

      -- Test RunService events
      runService.Heartbeat:Connect(function (deltaTime)
        -- Game loop logic here
      end)

      -- Test if running on server
      if runService:IsServer() then
        System.Console.WriteLine("Running on server!")
      end
    end
    return {
      Initialize = Initialize
    }
  end)

  -- <summary>
  -- Test class for physics interactions.
  -- </summary>
  namespace.class("PhysicsTest", function (namespace)
    local TestRaycast
    TestRaycast = function ()
      local origin = Vector3.new(0, 10, 0)
      local direction = Vector3.new(0, - 100, 0)

      -- Create raycast params
      local params_ = RaycastParams.new()

      -- Perform raycast
      local result = Roblox.Globals.getworkspace():Raycast(origin, direction, params_)
      if result ~= nil then
        System.Console.WriteLine("Hit: " .. result.Instance.Name)
        System.Console.WriteLine("Position: " .. result.Position:ToString())
        System.Console.WriteLine("Normal: " .. result.Normal:ToString())
        System.Console.WriteLine("Distance: " .. result.Distance)
      end
    end
    return {
      TestRaycast = TestRaycast
    }
  end)
end)

return true
