-- Generated by CSharp.lua Compiler
local System = _G.RobloxValidation.Runtime.System
System.namespace("RobloxValidation.Tests", function (namespace)
  -- <summary>
  -- Tests Vector3, CFrame, Color3 creation
  -- </summary>
  namespace.class("DataTypesTest", function (namespace)
    local TestVector3, TestCFrame, TestColor3, TestUDim2
    TestVector3 = function ()
      local v1 = Vector3.new(1, 2, 3)
      local v2 = Vector3.new(10)
      local zero = Vector3.zero
      local one = Vector3.one
      System.Console.WriteLine("X: " .. v1.X .. " Y: " .. v1.Y .. " Z: " .. v1.Z)
    end
    TestCFrame = function ()
      local cf1 = CFrame.new(0, 10, 0)
      local cf2 = CFrame.identity
      local position = cf1.Position
    end
    TestColor3 = function ()
      local c1 = Color3.new(1.0, 0.5, 0.25)
      local c2 = Color3.fromRGB(255, 128, 64)
      local c3 = Color3.fromHSV(0.5, 1.0, 1.0)
      System.Console.WriteLine("R: " .. c1.R)
    end
    TestUDim2 = function ()
      local ud1 = UDim2.new(0, 100, 0, 50)
      local ud2 = UDim2.fromScale(0.5, 0.5)
      local ud3 = UDim2.fromOffset(100, 100)
    end
    return {
      TestVector3 = TestVector3,
      TestCFrame = TestCFrame,
      TestColor3 = TestColor3,
      TestUDim2 = TestUDim2
    }
  end)
end)

return true
