-- Generated by CSharp.lua Compiler
local System = _G.RobloxValidation.Runtime.System
System.namespace("RobloxValidation.Tests", function (namespace)
  -- <summary>
  -- Tests that game.GetService&lt;T&gt;() transpiles to game:GetService("T")
  -- </summary>
  namespace.class("GetServiceTest", function (namespace)
    local TestGetService
    TestGetService = function ()
      -- Use explicit Globals.game to trigger MemberAccessExpression path
      -- which properly applies XML metadata templates
      local players = game:GetService("Players")
      local workspace_ = game:GetService("Workspace")
      local runService = game:GetService("RunService")
      local lighting = game:GetService("Lighting")
    end
    return {
      TestGetService = TestGetService
    }
  end)
end)

return true
