-- Generated by CSharp.lua Compiler
local System = _G.RobloxValidation.Runtime.System
System.namespace("RobloxValidation.Tests", function (namespace)
  -- <summary>
  -- Tests Instance creation, Clone, and Destroy
  -- </summary>
  namespace.class("InstanceCreationTest", function (namespace)
    local TestInstanceNew, TestInstanceNewWithParent, TestClone, TestDestroy
    TestInstanceNew = function ()
      -- Create a new Part instance
      local part = Instance.new("Part")
      part.Name = "MyPart"
      part.Position = Vector3.new(0, 10, 0)
      part.Parent = workspace
    end
    TestInstanceNewWithParent = function ()
      -- Create a new Model with parent
      local model = Instance.new("Model", workspace)
      model.Name = "MyModel"
    end
    TestClone = function ()
      local original = workspace:FindFirstChild("Template")
      if original ~= nil then
        local clone = original:Clone()
        clone.Name = "ClonedTemplate"
        clone.Parent = workspace
      end
    end
    TestDestroy = function ()
      local part = workspace:FindFirstChild("PartToDestroy")
      if part ~= nil then
        part:Destroy()
      end
    end
    return {
      TestInstanceNew = TestInstanceNew,
      TestInstanceNewWithParent = TestInstanceNewWithParent,
      TestClone = TestClone,
      TestDestroy = TestDestroy
    }
  end)
end)

return true
