-- Generated by CSharp.lua Compiler
local System = _G.RobloxValidation.Runtime.System
System.namespace("RobloxValidation.Tests", function (namespace)
  -- <summary>
  -- Tests null-conditional operator (?.) transpilation
  -- </summary>
  namespace.class("NullConditionalTest", function (namespace)
    local TestNullConditionalMethod, TestNullConditionalProperty, TestNullConditionalChain
    TestNullConditionalMethod = function ()
      -- Use ?. to safely call methods on potentially null instances
      local part = workspace:FindFirstChild("MaybeExists")
      local default = part
      if default ~= nil then
        default = default:FindFirstChildOfClass("Humanoid")
      end
      local humanoid = default
      local extern = humanoid
      if extern ~= nil then
        extern:TakeDamage(10)
      end
    end
    TestNullConditionalProperty = function ()
      -- Use ?. to safely access properties
      local player = game:GetService("Players").LocalPlayer
      local default = player
      if default ~= nil then
        default = default.Character
      end
      local character = default
      local extern = character
      if extern ~= nil then
        extern = extern.Name
      end
      local name = extern
      System.Console.WriteLine("Character: " .. (name or "none"))
    end
    TestNullConditionalChain = function ()
      -- Chain multiple null-conditional operators
      local default = workspace:FindFirstChild("Model")
      if default ~= nil then
        default = default:FindFirstChildOfClass("Humanoid")
      end
      local humanoid = default

      local extern = humanoid
      if extern ~= nil then
        extern = extern.Health
      end
      local health = extern
      if health ~= nil then
        System.Console.WriteLine("Health: " .. health:ToString())
      end
    end
    return {
      TestNullConditionalMethod = TestNullConditionalMethod,
      TestNullConditionalProperty = TestNullConditionalProperty,
      TestNullConditionalChain = TestNullConditionalChain
    }
  end)
end)

return true
