-- Generated by CSharp.lua Compiler
local System = _G.RobloxValidation.Runtime.System
local Roblox = _G.RobloxValidation.Runtime.Roblox
System.namespace("RobloxValidation.Tests", function (namespace)
  -- <summary>
  -- Tests ScriptSignal.Connect with lambdas
  -- </summary>
  namespace.class("EventsTest", function (namespace)
    local TestPlayerAdded, TestCharacterAdded, TestTouched
    TestPlayerAdded = function ()
      local players = game:GetService("Players")
      players.PlayerAdded:Connect(function (player)
        System.Console.WriteLine("Player joined: " .. player:getName())
      end)
    end
    TestCharacterAdded = function ()
      local players = game:GetService("Players")
      players.PlayerAdded:Connect(function (player)
        player.CharacterAdded:Connect(function (character)
          local humanoid = character:FindFirstChildOfClass("Humanoid")
          if humanoid ~= nil then
            humanoid:TakeDamage(10)
          end
        end)
      end)
    end
    TestTouched = function ()
      local part = workspace:FindFirstChild("Part")
      if part ~= nil and part:IsA("BasePart") then
        (System.cast(Roblox.BasePart, part)).Touched:Connect(function (otherPart)
          System.Console.WriteLine("Touched: " .. otherPart.Name)
        end)
      end
    end
    return {
      TestPlayerAdded = TestPlayerAdded,
      TestCharacterAdded = TestCharacterAdded,
      TestTouched = TestTouched
    }
  end)
end)

return true
