-- Generated by CSharp.lua Compiler
local System = _G.RobloxValidation.Runtime.System
System.namespace("RobloxValidation.Tests", function (namespace)
  -- <summary>
  -- Tests generated types including enums
  -- Note: Roblox uses Enum.Material in Lua, but C# uses Material directly
  -- The transpiler handles mapping C# enum access to Lua's Enum.{EnumName} pattern
  -- </summary>
  namespace.class("GeneratedTypesTest", function (namespace)
    local TestEnumAccess, TestEnumGetItems
    TestEnumAccess = function ()
      -- Access enum items directly in C# (transpiler maps to Enum.Material.Plastic in Lua)
      local material = Enum.Material.Plastic
      local material2 = Enum.Material.Brick

      System.Console.WriteLine("Material: " .. material.Name)
      System.Console.WriteLine("Material value: " .. material.Value)
    end
    TestEnumGetItems = function ()
      -- Test GetEnumItems method
      local items = Enum.Material:GetEnumItems()
      System.Console.WriteLine("Enum items count: " .. #items)
    end
    return {
      TestEnumAccess = TestEnumAccess,
      TestEnumGetItems = TestEnumGetItems
    }
  end)
end)

return true
