-- Generated by CSharp.lua Compiler
local System = _G.RobloxValidation.Runtime.System
System.namespace("RobloxValidation.Tests", function (namespace)
  -- <summary>
  -- Tests Instance methods: FindFirstChild, FindFirstChildOfClass, IsA, etc.
  -- </summary>
  namespace.class("InstanceMethodsTest", function (namespace)
    local TestFindFirstChild, TestFindFirstChildOfClass, TestIsA, TestWaitForChild, TestGetChildren
    TestFindFirstChild = function ()
      local part = workspace:FindFirstChild("Part")
      local partRecursive = workspace:FindFirstChild("Part", true)
    end
    TestFindFirstChildOfClass = function ()
      local part = workspace:FindFirstChild("Model")
      if part ~= nil then
        local humanoid = part:FindFirstChildOfClass("Humanoid")
      end
    end
    TestIsA = function ()
      local part = workspace:FindFirstChild("TestPart")
      if part ~= nil and part:IsA("BasePart") then
        System.Console.WriteLine("It's a BasePart!")
      end
    end
    TestWaitForChild = function ()
      local part = workspace:WaitForChild("Part")
      local partWithTimeout = workspace:WaitForChild("Part", 5.0)
    end
    TestGetChildren = function ()
      local children = workspace:GetChildren()
      local descendants = workspace:GetDescendants()
    end
    return {
      TestFindFirstChild = TestFindFirstChild,
      TestFindFirstChildOfClass = TestFindFirstChildOfClass,
      TestIsA = TestIsA,
      TestWaitForChild = TestWaitForChild,
      TestGetChildren = TestGetChildren
    }
  end)
end)

return true
