-- Generated by CSharp.lua Compiler
local System = _G.RobloxValidation.Runtime.System
System.namespace("RobloxValidation.Tests", function (namespace)
  -- <summary>
  -- Tests task, debug, os library calls
  -- </summary>
  namespace.class("LuaLibrariesTest", function (namespace)
    local TestTask, TestDebug, TestOs
    TestTask = function ()
      task.spawn(function ()
        System.Console.WriteLine("Spawned!")
      end)
      task.delay(1.0, function ()
        System.Console.WriteLine("Delayed!")
      end)
      task.wait(0.5)
      task.defer(function ()
        System.Console.WriteLine("Deferred!")
      end)
    end
    TestDebug = function ()
      debug.profilebegin("MyProfile")
      -- do work
      debug.profileend()
      local trace = debug.traceback(nil, nil)
    end
    TestOs = function ()
      local time_ = os.time()
      local clock = os.clock()
      System.Console.WriteLine("Time: " .. time_ .. " Clock: " .. clock)
    end
    return {
      TestTask = TestTask,
      TestDebug = TestDebug,
      TestOs = TestOs
    }
  end)
end)

return true
