-- Generated by CSharp.lua Compiler
local System = _G.RobloxValidation.Runtime.System
return function (path)
  return System.init({
    path = path,
    files = {
      "DataTypesTest",
      "EventsTest",
      "GetServiceTest",
      "InstanceCreationTest",
      "InstanceMethodsTest",
      "LuaLibrariesTest",
      "NullConditionalTest"
    },
    types = {
      "RobloxValidation.Tests.DataTypesTest",
      "RobloxValidation.Tests.EventsTest",
      "RobloxValidation.Tests.GetServiceTest",
      "RobloxValidation.Tests.InstanceCreationTest",
      "RobloxValidation.Tests.InstanceMethodsTest",
      "RobloxValidation.Tests.LuaLibrariesTest",
      "RobloxValidation.Tests.NullConditionalTest"
    },
    assembly = {
      Company = "TestProject",
      Configuration = "Debug",
      FileVersion = "1.0.0.0",
      InformationalVersion = "1.0.0+8afcd61a424cbfde5d8ecb8ac341beb85d872027",
      Product = "TestProject",
      Title = "TestProject",
      Version = "1.0.0.0"
    }
  })
end
