-- Generated by CSharp.lua Compiler
local System = _G.TestGame.System
local TestGame
System.import(function (out)
  TestGame = _G.TestGame.TestGame
end)
System.namespace("TestGame", function (namespace)
  -- <summary>
  -- Handles spawning buildings at player positions.
  -- Adapts building patterns from GameScene for shop purchases.
  -- </summary>
  namespace.class("BuildingSpawner", function (namespace)
    local _buildingCounter, LightStone, MediumStone, DarkStone, DarkTimber, MediumTimber, LightWood, OldWood, 
    PlasterWhite, PlasterCream, RoofTerracotta, RoofBrown, RoofSlate, ThatchYellow, TreeGreen, TreeDark, 
    TrunkBrown, WaterDeep, WindowBlue, BannerRed, GetSpawnPosition, GetUniqueName, Block, SpawnTree, 
    SpawnWell, SpawnSmallHouse, SpawnMarketStall, SpawnLargeHouse, SpawnTower, SpawnWindmill, SpawnChurch, static
    static = function (this)
      LightStone = Color3.fromRGB(180, 175, 165)
      MediumStone = Color3.fromRGB(140, 135, 125)
      DarkStone = Color3.fromRGB(95, 90, 85)
      DarkTimber = Color3.fromRGB(75, 50, 30)
      MediumTimber = Color3.fromRGB(101, 67, 33)
      LightWood = Color3.fromRGB(160, 130, 100)
      OldWood = Color3.fromRGB(90, 75, 60)
      PlasterWhite = Color3.fromRGB(250, 245, 235)
      PlasterCream = Color3.fromRGB(245, 235, 210)
      RoofTerracotta = Color3.fromRGB(180, 100, 70)
      RoofBrown = Color3.fromRGB(110, 75, 55)
      RoofSlate = Color3.fromRGB(70, 75, 80)
      ThatchYellow = Color3.fromRGB(190, 170, 110)
      TreeGreen = Color3.fromRGB(45, 95, 35)
      TreeDark = Color3.fromRGB(30, 70, 25)
      TrunkBrown = Color3.fromRGB(80, 55, 35)
      WaterDeep = Color3.fromRGB(45, 100, 140)
      WindowBlue = Color3.fromRGB(170, 210, 240)
      BannerRed = Color3.fromRGB(180, 40, 45)
    end
    _buildingCounter = 0
    -- <summary>
    -- Gets a spawn position in front of the player at ground level.
    -- </summary>
    GetSpawnPosition = function (player, distance)
      local character = player.Character
      if character == nil then
        return Vector3.new(0, 0, 0)
      end

      local rootPart = character:FindFirstChild("HumanoidRootPart")
      if rootPart == nil then
        return Vector3.new(0, 0, 0)
      end

      local cframe = rootPart.CFrame
      local lookVector = cframe.LookVector
      local playerPos = rootPart.Position

      return Vector3.new(playerPos.X + lookVector.X * distance, 0, playerPos.Z + lookVector.Z * distance)
    end
    GetUniqueName = function (baseName)
      _buildingCounter = _buildingCounter + 1
      return baseName .. "_" .. _buildingCounter
    end
    Block = function (name, position, size, color)
      local block = TestGame.SpawnableBox(name, position, size, color)
      block:Spawn()
    end
    SpawnTree = function (pos)
      local name = GetUniqueName("Tree")
      local x = pos.X local y = pos.Y local z = pos.Z
      local height = 10
      local canopySize = 7

      -- Trunk
      Block(name .. "_Trunk", Vector3.new(x, y + height / 2, z), Vector3.new(1.5, height, 1.5), TrunkBrown)

      -- Canopy layers
      Block(name .. "_Canopy1", Vector3.new(x, y + height + canopySize / 2, z), Vector3.new(canopySize, canopySize, canopySize), TreeGreen)
      Block(name .. "_Canopy2", Vector3.new(x + 1, y + height + canopySize / 2 + 1, z + 1), Vector3.new(canopySize * 0.7, canopySize * 0.8, canopySize * 0.7), TreeDark)

      System.Console.WriteLine("Spawned " .. name)
    end
    SpawnWell = function (pos)
      local name = GetUniqueName("Well")
      local x = pos.X local y = pos.Y local z = pos.Z

      Block(name .. "_Base", Vector3.new(x, y + 1.5, z), Vector3.new(5, 3, 5), MediumStone)
      Block(name .. "_Water", Vector3.new(x, y + 2.2, z), Vector3.new(3.5, 1, 3.5), WaterDeep)
      Block(name .. "_PostL", Vector3.new(x - 2, y + 5, z), Vector3.new(0.6, 7, 0.6), DarkTimber)
      Block(name .. "_PostR", Vector3.new(x + 2, y + 5, z), Vector3.new(0.6, 7, 0.6), DarkTimber)
      Block(name .. "_Beam", Vector3.new(x, y + 8.5, z), Vector3.new(5, 0.6, 0.8), DarkTimber)
      Block(name .. "_Roof", Vector3.new(x, y + 9.5, z), Vector3.new(6, 1.5, 4), RoofBrown)

      System.Console.WriteLine("Spawned " .. name)
    end
    SpawnSmallHouse = function (pos)
      local name = GetUniqueName("SmallHouse")
      local x = pos.X local z = pos.Z
      local w = 10 local h = 8 local d = 10
      local beam = 0.5

      -- First floor
      Block(name .. "_Floor1", Vector3.new(x, h * 0.55 / 2, z), Vector3.new(w, h * 0.55, d), PlasterCream)

      -- Corner posts
      Block(name .. "_Post1", Vector3.new(x - w / 2 + beam / 2, h * 0.55 / 2, z + d / 2 - beam / 2), Vector3.new(beam, h * 0.55, beam), DarkTimber)
      Block(name .. "_Post2", Vector3.new(x + w / 2 - beam / 2, h * 0.55 / 2, z + d / 2 - beam / 2), Vector3.new(beam, h * 0.55, beam), DarkTimber)

      -- Horizontal beams
      Block(name .. "_HBeam", Vector3.new(x, h * 0.55, z + d / 2), Vector3.new(w + 0.2, beam, beam), DarkTimber)

      -- Roof
      Block(name .. "_RoofL", Vector3.new(x - w / 4, h * 0.55 + h * 0.35 / 2, z), Vector3.new(w / 2 + 1, h * 0.35, d + 2), RoofTerracotta)
      Block(name .. "_RoofR", Vector3.new(x + w / 4, h * 0.55 + h * 0.35 / 2, z), Vector3.new(w / 2 + 1, h * 0.35, d + 2), RoofTerracotta)

      -- Door
      Block(name .. "_Door", Vector3.new(x, 2, z + d / 2 + 0.15), Vector3.new(2, 4, 0.3), DarkTimber)

      -- Window
      Block(name .. "_Win", Vector3.new(x + w / 3, h * 0.35, z + d / 2 + 0.15), Vector3.new(1.5, 1.8, 0.2), WindowBlue)

      System.Console.WriteLine("Spawned " .. name)
    end
    SpawnMarketStall = function (pos)
      local name = GetUniqueName("MarketStall")
      local x = pos.X local z = pos.Z

      -- Counter
      Block(name .. "_Counter", Vector3.new(x, 2, z), Vector3.new(8, 1.5, 4), LightWood)
      Block(name .. "_Front", Vector3.new(x, 1, z + 2), Vector3.new(8, 2, 0.5), OldWood)

      -- Support posts
      Block(name .. "_PostL", Vector3.new(x - 3.5, 3.5, z - 1.5), Vector3.new(0.5, 7, 0.5), MediumTimber)
      Block(name .. "_PostR", Vector3.new(x + 3.5, 3.5, z - 1.5), Vector3.new(0.5, 7, 0.5), MediumTimber)

      -- Canopy
      Block(name .. "_Canopy", Vector3.new(x, 7.5, z), Vector3.new(10, 0.4, 6), BannerRed)

      -- Goods
      Block(name .. "_Goods1", Vector3.new(x - 2, 3, z), Vector3.new(1.5, 0.8, 1.5), Color3.fromRGB(200, 60, 70))
      Block(name .. "_Goods2", Vector3.new(x, 3, z), Vector3.new(1.5, 0.8, 1.5), Color3.fromRGB(240, 200, 80))
      Block(name .. "_Goods3", Vector3.new(x + 2, 3, z), Vector3.new(1.5, 0.8, 1.5), Color3.fromRGB(150, 80, 170))

      System.Console.WriteLine("Spawned " .. name)
    end
    SpawnLargeHouse = function (pos)
      local name = GetUniqueName("LargeHouse")
      local x = pos.X local z = pos.Z
      local w = 14 local h = 11 local d = 12
      local beam = 0.6
      local firstFloorH = h * 0.55
      local secondFloorH = h * 0.45
      local jettyOverhang = 1.5

      -- First floor
      Block(name .. "_Floor1", Vector3.new(x, firstFloorH / 2, z), Vector3.new(w, firstFloorH, d), PlasterWhite)

      -- Corner posts
      Block(name .. "_Post_FL", Vector3.new(x - w / 2 + beam / 2, firstFloorH / 2, z + d / 2 - beam / 2), Vector3.new(beam, firstFloorH, beam), DarkTimber)
      Block(name .. "_Post_FR", Vector3.new(x + w / 2 - beam / 2, firstFloorH / 2, z + d / 2 - beam / 2), Vector3.new(beam, firstFloorH, beam), DarkTimber)

      -- Horizontal beams
      Block(name .. "_HBeam_Top", Vector3.new(x, firstFloorH, z + d / 2), Vector3.new(w + 0.2, beam, beam), DarkTimber)

      -- Second floor with jetty
      local floor2W = w + jettyOverhang * 2
      local floor2D = d + jettyOverhang * 2
      local floor2Y = firstFloorH + secondFloorH / 2

      Block(name .. "_Jetty", Vector3.new(x, firstFloorH + 0.3, z + d / 2 + jettyOverhang / 2), Vector3.new(floor2W + 0.5, 0.6, jettyOverhang + 0.5), DarkTimber)
      Block(name .. "_Floor2", Vector3.new(x, floor2Y, z), Vector3.new(floor2W, secondFloorH, floor2D), PlasterWhite)

      -- Roof
      local roofH = h * 0.5
      Block(name .. "_RoofL", Vector3.new(x - floor2W / 4, firstFloorH + secondFloorH + roofH / 2, z), Vector3.new(floor2W / 2 + 1.5, roofH, floor2D + 3), RoofTerracotta)
      Block(name .. "_RoofR", Vector3.new(x + floor2W / 4, firstFloorH + secondFloorH + roofH / 2, z), Vector3.new(floor2W / 2 + 1.5, roofH, floor2D + 3), RoofTerracotta)

      -- Door
      Block(name .. "_Door", Vector3.new(x, 2.5, z + d / 2 + 0.15), Vector3.new(2.5, 5, 0.4), DarkTimber)

      -- Windows
      Block(name .. "_Win1", Vector3.new(x - w / 3, firstFloorH * 0.6, z + d / 2 + 0.15), Vector3.new(1.8, 2.2, 0.2), WindowBlue)
      Block(name .. "_Win2", Vector3.new(x + w / 3, firstFloorH * 0.6, z + d / 2 + 0.15), Vector3.new(1.8, 2.2, 0.2), WindowBlue)

      -- Chimney
      Block(name .. "_Chimney", Vector3.new(x + w / 3, firstFloorH + secondFloorH + roofH + 1, z - d / 4), Vector3.new(2, 4, 2), DarkStone)

      System.Console.WriteLine("Spawned " .. name)
    end
    SpawnTower = function (pos)
      local name = GetUniqueName("Tower")
      local x = pos.X local y = pos.Y local z = pos.Z
      local height = 24
      local size = 10

      -- Main tower body
      Block(name .. "_Base", Vector3.new(x, y + height / 2, z), Vector3.new(size, height, size), DarkStone)
      Block(name .. "_Mid", Vector3.new(x, y + height / 2, z), Vector3.new(size - 1, height - 4, size - 1), MediumStone)

      -- Top platform
      Block(name .. "_Platform", Vector3.new(x, y + height + 0.5, z), Vector3.new(size + 2, 1, size + 2), LightStone)

      -- Conical roof
      Block(name .. "_Roof1", Vector3.new(x, y + height + 3, z), Vector3.new(8, 4, 8), RoofSlate)
      Block(name .. "_Roof2", Vector3.new(x, y + height + 6, z), Vector3.new(5, 4, 5), RoofSlate)
      Block(name .. "_Roof3", Vector3.new(x, y + height + 9, z), Vector3.new(2, 3, 2), RoofSlate)

      -- Windows
      Block(name .. "_Win1", Vector3.new(x, y + height * 0.7, z + size / 2 + 0.1), Vector3.new(2, 4, 0.3), WindowBlue)
      Block(name .. "_Win2", Vector3.new(x + size / 2 + 0.1, y + height * 0.7, z), Vector3.new(0.3, 4, 2), WindowBlue)

      -- Door
      Block(name .. "_Door", Vector3.new(x, y + 3, z + size / 2 + 0.1), Vector3.new(2.5, 6, 0.3), DarkTimber)

      System.Console.WriteLine("Spawned " .. name)
    end
    SpawnWindmill = function (pos)
      local name = GetUniqueName("Windmill")
      local x = pos.X local y = pos.Y local z = pos.Z

      -- Main building
      Block(name .. "_Base", Vector3.new(x, y + 8, z), Vector3.new(12, 16, 12), LightStone)

      -- Conical roof
      Block(name .. "_Roof1", Vector3.new(x, y + 18, z), Vector3.new(14, 4, 14), ThatchYellow)
      Block(name .. "_Roof2", Vector3.new(x, y + 21, z), Vector3.new(10, 4, 10), ThatchYellow)
      Block(name .. "_Roof3", Vector3.new(x, y + 24, z), Vector3.new(6, 4, 6), ThatchYellow)
      Block(name .. "_Roof4", Vector3.new(x, y + 26.5, z), Vector3.new(3, 3, 3), ThatchYellow)

      -- Mill sails
      Block(name .. "_Hub", Vector3.new(x, y + 12, z + 6.5), Vector3.new(3, 3, 1), DarkTimber)
      Block(name .. "_Sail1", Vector3.new(x, y + 20, z + 7), Vector3.new(2, 14, 0.3), LightWood)
      Block(name .. "_Sail2", Vector3.new(x, y + 4, z + 7), Vector3.new(2, 14, 0.3), LightWood)
      Block(name .. "_Sail3", Vector3.new(x - 8, y + 12, z + 7), Vector3.new(14, 2, 0.3), LightWood)
      Block(name .. "_Sail4", Vector3.new(x + 8, y + 12, z + 7), Vector3.new(14, 2, 0.3), LightWood)

      -- Door
      Block(name .. "_Door", Vector3.new(x, y + 3, z + 6.2), Vector3.new(3, 6, 0.4), DarkTimber)

      System.Console.WriteLine("Spawned " .. name)
    end
    SpawnChurch = function (pos)
      local name = GetUniqueName("Church")
      local x = pos.X local y = pos.Y local z = pos.Z

      -- Main nave
      Block(name .. "_Nave", Vector3.new(x, y + 8, z), Vector3.new(14, 16, 26), LightStone)

      -- Bell tower
      Block(name .. "_Tower", Vector3.new(x, y + 20, z + 10), Vector3.new(8, 40, 8), MediumStone)
      Block(name .. "_TowerTop", Vector3.new(x, y + 42, z + 10), Vector3.new(10, 4, 10), LightStone)

      -- Spire
      Block(name .. "_Spire1", Vector3.new(x, y + 47, z + 10), Vector3.new(7, 8, 7), RoofSlate)
      Block(name .. "_Spire2", Vector3.new(x, y + 53, z + 10), Vector3.new(4, 8, 4), RoofSlate)
      Block(name .. "_Spire3", Vector3.new(x, y + 58, z + 10), Vector3.new(1.5, 6, 1.5), RoofSlate)

      -- Cross
      Block(name .. "_Cross", Vector3.new(x, y + 62, z + 10), Vector3.new(0.5, 3, 0.5), Color3.fromRGB(220, 180, 80))
      Block(name .. "_CrossArm", Vector3.new(x, y + 61, z + 10), Vector3.new(2, 0.5, 0.5), Color3.fromRGB(220, 180, 80))

      -- Roof
      Block(name .. "_RoofL", Vector3.new(x - 4.5, y + 18, z), Vector3.new(7, 6, 28), RoofSlate)
      Block(name .. "_RoofR", Vector3.new(x + 4.5, y + 18, z), Vector3.new(7, 6, 28), RoofSlate)

      -- Entrance
      Block(name .. "_Door", Vector3.new(x, y + 4, z + 13.5), Vector3.new(4, 8, 0.5), DarkTimber)
      Block(name .. "_Arch", Vector3.new(x, y + 9, z + 13.5), Vector3.new(6, 3, 1), LightStone)

      -- Rose window
      Block(name .. "_Window", Vector3.new(x, y + 12, z + 13.5), Vector3.new(5, 5, 0.3), WindowBlue)

      System.Console.WriteLine("Spawned " .. name)
    end
    return {
      GetSpawnPosition = GetSpawnPosition,
      SpawnTree = SpawnTree,
      SpawnWell = SpawnWell,
      SpawnSmallHouse = SpawnSmallHouse,
      SpawnMarketStall = SpawnMarketStall,
      SpawnLargeHouse = SpawnLargeHouse,
      SpawnTower = SpawnTower,
      SpawnWindmill = SpawnWindmill,
      SpawnChurch = SpawnChurch,
      static = static
    }
  end)
end)

return true
