-- Generated by CSharp.lua Compiler
local System = _G.TestGame.System
System.namespace("TestGame", function (namespace)
  -- <summary>
  -- Manages player currency with passive income.
  -- Provides 10 coins every 5 seconds automatically.
  -- </summary>
  namespace.class("CurrencyManager", function (namespace)
    local getCoins, StartPassiveIncome, Update, AddCoins, CanAfford, TrySpend, __ctor__
    -- <summary>
    -- Creates a new currency manager with the specified starting coins.
    -- </summary>
    __ctor__ = function (this, startingCoins)
      this._coins = startingCoins
      this._timeSinceLastIncome = 0
    end
    getCoins = function (this)
      return this._coins
    end
    -- <summary>
    -- Starts the passive income system using RunService.Heartbeat.
    -- Call this once after creating the manager.
    -- </summary>
    StartPassiveIncome = function (this)
      local runService = game:GetService("RunService")
      runService.Heartbeat:Connect(System.fn(this, Update))
    end
    -- <summary>
    -- Called every frame to update passive income timer.
    -- </summary>
    Update = function (this, deltaTime)
      this._timeSinceLastIncome = this._timeSinceLastIncome + deltaTime

      if this._timeSinceLastIncome >= this._incomeInterval then
        AddCoins(this, this._incomeAmount)
        this._timeSinceLastIncome = 0
      end
    end
    -- <summary>
    -- Adds coins to the player's balance.
    -- </summary>
    AddCoins = function (this, amount)
      this._coins = this._coins + amount
      local default = this.OnCoinsChanged
      if default ~= nil then
        default(this._coins)
      end
    end
    -- <summary>
    -- Checks if the player can afford a purchase.
    -- </summary>
    CanAfford = function (this, amount)
      return this._coins >= amount
    end
    -- <summary>
    -- Attempts to spend coins. Returns true if successful.
    -- </summary>
    TrySpend = function (this, amount)
      if this._coins >= amount then
        this._coins = this._coins - amount
        local default = this.OnCoinsChanged
        if default ~= nil then
          default(this._coins)
        end
        return true
      end
      return false
    end
    return {
      _coins = 0,
      _timeSinceLastIncome = 0,
      _incomeInterval = 5.0,
      _incomeAmount = 10,
      getCoins = getCoins,
      StartPassiveIncome = StartPassiveIncome,
      AddCoins = AddCoins,
      CanAfford = CanAfford,
      TrySpend = TrySpend,
      __ctor__ = __ctor__
    }
  end)
end)

return true
