-- Generated by CSharp.lua Compiler
local System = _G.TestGame.System
local TestGame
System.import(function (out)
  TestGame = _G.TestGame.TestGame
end)
System.namespace("TestGame", function (namespace)
  -- <summary>
  -- Sets up the game scene with a castle and village.
  -- </summary>
  namespace.class("GameScene", function (namespace)
    local StoneGray, DarkStone, TimberBrown, PlasterWhite, RoofRed, RoofDark, Setup, SpawnBlock, 
    BuildCastleWalls, BuildTowers, BuildGate, BuildVillage, BuildTimberHouse, BuildWell, BuildMarketStall, static
    static = function (this)
      StoneGray = Color3.fromRGB(130, 130, 130)
      DarkStone = Color3.fromRGB(90, 90, 90)
      TimberBrown = Color3.fromRGB(101, 67, 33)
      PlasterWhite = Color3.fromRGB(245, 240, 230)
      RoofRed = Color3.fromRGB(139, 69, 49)
      RoofDark = Color3.fromRGB(80, 50, 30)
    end
    Setup = function ()
      System.Console.WriteLine("Building medieval scene...")

      -- Ground/floor - larger for village
      SpawnBlock("Floor", Vector3.new(0, - 0.5, 0), Vector3.new(500, 1, 500), Color3.fromRGB(50, 120, 50))

      -- Dirt path from village to castle
      SpawnBlock("Path", Vector3.new(0, - 0.4, 55), Vector3.new(8, 0.2, 70), Color3.fromRGB(139, 119, 101))

      -- Build the castle
      BuildCastleWalls()
      BuildTowers()
      BuildGate()

      -- Build the village outside the castle
      BuildVillage()

      System.Console.WriteLine("Medieval scene complete!")
    end
    SpawnBlock = function (name, position, size, color)
      local block = TestGame.SpawnableBox(name, position, size, color)
      block:Spawn()
    end
    BuildCastleWalls = function ()
      local wallHeight = 12
      local wallThickness = 3
      local castleSize = 40
      local halfSize = castleSize / 2
      local gateWidth = 10

      -- Back wall (full)
      SpawnBlock("BackWall", Vector3.new(0, wallHeight / 2, - halfSize), Vector3.new(castleSize, wallHeight, wallThickness), StoneGray)

      -- Front wall - left section (with gap for gate)
      SpawnBlock("FrontWallLeft", Vector3.new(- halfSize / 2 - gateWidth / 4, wallHeight / 2, halfSize), Vector3.new(halfSize - gateWidth / 2, wallHeight, wallThickness), StoneGray)

      -- Front wall - right section
      SpawnBlock("FrontWallRight", Vector3.new(halfSize / 2 + gateWidth / 4, wallHeight / 2, halfSize), Vector3.new(halfSize - gateWidth / 2, wallHeight, wallThickness), StoneGray)

      -- Left wall
      SpawnBlock("LeftWall", Vector3.new(- halfSize, wallHeight / 2, 0), Vector3.new(wallThickness, wallHeight, castleSize), StoneGray)

      -- Right wall
      SpawnBlock("RightWall", Vector3.new(halfSize, wallHeight / 2, 0), Vector3.new(wallThickness, wallHeight, castleSize), StoneGray)
    end
    BuildTowers = function ()
      local towerHeight = 18
      local towerSize = 8
      local castleSize = 40
      local halfSize = castleSize / 2

      -- Four corner towers
      SpawnBlock("TowerFL", Vector3.new(- halfSize, towerHeight / 2, halfSize), Vector3.new(towerSize, towerHeight, towerSize), DarkStone)
      SpawnBlock("TowerFR", Vector3.new(halfSize, towerHeight / 2, halfSize), Vector3.new(towerSize, towerHeight, towerSize), DarkStone)
      SpawnBlock("TowerBL", Vector3.new(- halfSize, towerHeight / 2, - halfSize), Vector3.new(towerSize, towerHeight, towerSize), DarkStone)
      SpawnBlock("TowerBR", Vector3.new(halfSize, towerHeight / 2, - halfSize), Vector3.new(towerSize, towerHeight, towerSize), DarkStone)

      -- Tower tops (crenellations)
      local topHeight = 2
      local topSize = towerSize + 2
      local topY = towerHeight + topHeight / 2
      SpawnBlock("TowerTopFL", Vector3.new(- halfSize, topY, halfSize), Vector3.new(topSize, topHeight, topSize), DarkStone)
      SpawnBlock("TowerTopFR", Vector3.new(halfSize, topY, halfSize), Vector3.new(topSize, topHeight, topSize), DarkStone)
      SpawnBlock("TowerTopBL", Vector3.new(- halfSize, topY, - halfSize), Vector3.new(topSize, topHeight, topSize), DarkStone)
      SpawnBlock("TowerTopBR", Vector3.new(halfSize, topY, - halfSize), Vector3.new(topSize, topHeight, topSize), DarkStone)
    end
    BuildGate = function ()
      local castleSize = 40
      local halfSize = castleSize / 2
      local gateWidth = 10
      local gateHeight = 8
      local archHeight = 4

      -- Gate arch (top of gate opening)
      SpawnBlock("GateArch", Vector3.new(0, gateHeight + archHeight / 2, halfSize), Vector3.new(gateWidth + 2, archHeight, 4), DarkStone)

      -- Gate pillars on each side
      SpawnBlock("GatePillarLeft", Vector3.new(- gateWidth / 2 - 1, (gateHeight + archHeight) / 2, halfSize), Vector3.new(2, gateHeight + archHeight, 4), DarkStone)

      SpawnBlock("GatePillarRight", Vector3.new(gateWidth / 2 + 1, (gateHeight + archHeight) / 2, halfSize), Vector3.new(2, gateHeight + archHeight, 4), DarkStone)
    end
    BuildVillage = function ()
      -- Village is positioned outside the castle gate (positive Z)
      local villageZ = 70

      -- Row of houses on the left side of the path
      BuildTimberHouse("House1", Vector3.new(- 20, 0, villageZ), 12, 10, 14)
      BuildTimberHouse("House2", Vector3.new(- 20, 0, villageZ + 25), 10, 8, 12)
      BuildTimberHouse("House3", Vector3.new(- 35, 0, villageZ + 10), 14, 12, 16)

      -- Row of houses on the right side of the path
      BuildTimberHouse("House4", Vector3.new(20, 0, villageZ), 11, 9, 13)
      BuildTimberHouse("House5", Vector3.new(20, 0, villageZ + 25), 13, 11, 15)
      BuildTimberHouse("House6", Vector3.new(35, 0, villageZ + 10), 10, 8, 12)

      -- A larger tavern/inn at the end
      BuildTimberHouse("Tavern", Vector3.new(0, 0, villageZ + 45), 18, 12, 20)

      -- Well in the village center
      BuildWell(Vector3.new(0, 0, villageZ + 15))

      -- Market stalls
      BuildMarketStall("Stall1", Vector3.new(- 8, 0, villageZ + 15))
      BuildMarketStall("Stall2", Vector3.new(8, 0, villageZ + 15))
    end
    BuildTimberHouse = function (name, pos, width, height, depth)
      local x = pos.X
      local z = pos.Z

      -- Main white plaster walls
      SpawnBlock(name .. "_Body", Vector3.new(x, height / 2, z), Vector3.new(width, height, depth), PlasterWhite)

      -- Timber frame - horizontal beams
      local beamThickness = 0.8

      -- Bottom beam
      SpawnBlock(name .. "_BeamBot", Vector3.new(x, beamThickness / 2, z), Vector3.new(width + 0.2, beamThickness, depth + 0.2), TimberBrown)

      -- Middle beam
      SpawnBlock(name .. "_BeamMid", Vector3.new(x, height / 2, z), Vector3.new(width + 0.2, beamThickness, depth + 0.2), TimberBrown)

      -- Top beam
      SpawnBlock(name .. "_BeamTop", Vector3.new(x, height - beamThickness / 2, z), Vector3.new(width + 0.2, beamThickness, depth + 0.2), TimberBrown)

      -- Vertical corner beams (front face)
      SpawnBlock(name .. "_CornerFL", Vector3.new(x - width / 2 + beamThickness / 2, height / 2, z + depth / 2), Vector3.new(beamThickness, height, beamThickness), TimberBrown)
      SpawnBlock(name .. "_CornerFR", Vector3.new(x + width / 2 - beamThickness / 2, height / 2, z + depth / 2), Vector3.new(beamThickness, height, beamThickness), TimberBrown)

      -- Diagonal cross beams on front (the classic X pattern)
      -- We'll simulate with two angled blocks - simplified as small blocks
      SpawnBlock(name .. "_CrossF1", Vector3.new(x - width / 4, height / 4, z + depth / 2 + 0.1), Vector3.new(beamThickness, height / 3, beamThickness), TimberBrown)
      SpawnBlock(name .. "_CrossF2", Vector3.new(x + width / 4, height / 4, z + depth / 2 + 0.1), Vector3.new(beamThickness, height / 3, beamThickness), TimberBrown)
      SpawnBlock(name .. "_CrossF3", Vector3.new(x - width / 4, height * 3 / 4, z + depth / 2 + 0.1), Vector3.new(beamThickness, height / 3, beamThickness), TimberBrown)
      SpawnBlock(name .. "_CrossF4", Vector3.new(x + width / 4, height * 3 / 4, z + depth / 2 + 0.1), Vector3.new(beamThickness, height / 3, beamThickness), TimberBrown)

      -- Peaked roof
      local roofHeight = height * 0.6
      local roofOverhang = 2

      -- Roof - two slanted sections (simplified as angled blocks)
      -- Left roof slope
      SpawnBlock(name .. "_RoofL", Vector3.new(x - width / 4, height + roofHeight / 2, z), Vector3.new(width / 2 + roofOverhang, roofHeight, depth + roofOverhang * 2), RoofRed)
      -- Right roof slope
      SpawnBlock(name .. "_RoofR", Vector3.new(x + width / 4, height + roofHeight / 2, z), Vector3.new(width / 2 + roofOverhang, roofHeight, depth + roofOverhang * 2), RoofRed)

      -- Roof peak
      SpawnBlock(name .. "_RoofPeak", Vector3.new(x, height + roofHeight - 0.5, z), Vector3.new(2, 1, depth + roofOverhang * 2), RoofDark)

      -- Door (dark opening)
      SpawnBlock(name .. "_Door", Vector3.new(x, 3, z + depth / 2 + 0.2), Vector3.new(3, 6, 0.5), Color3.fromRGB(50, 35, 25))

      -- Windows
      SpawnBlock(name .. "_Window1", Vector3.new(x - width / 3, height / 2 + 1, z + depth / 2 + 0.2), Vector3.new(2, 2, 0.3), Color3.fromRGB(180, 220, 255))
      SpawnBlock(name .. "_Window2", Vector3.new(x + width / 3, height / 2 + 1, z + depth / 2 + 0.2), Vector3.new(2, 2, 0.3), Color3.fromRGB(180, 220, 255))
    end
    BuildWell = function (pos)
      local x = pos.X
      local z = pos.Z

      -- Stone base
      SpawnBlock("Well_Base", Vector3.new(x, 1.5, z), Vector3.new(5, 3, 5), StoneGray)

      -- Water inside (blue)
      SpawnBlock("Well_Water", Vector3.new(x, 2.5, z), Vector3.new(3, 1, 3), Color3.fromRGB(64, 164, 223))

      -- Wooden posts
      SpawnBlock("Well_Post1", Vector3.new(x - 2, 4, z), Vector3.new(0.8, 5, 0.8), TimberBrown)
      SpawnBlock("Well_Post2", Vector3.new(x + 2, 4, z), Vector3.new(0.8, 5, 0.8), TimberBrown)

      -- Roof beam
      SpawnBlock("Well_Beam", Vector3.new(x, 6.5, z), Vector3.new(6, 0.8, 1), TimberBrown)

      -- Small roof
      SpawnBlock("Well_Roof", Vector3.new(x, 7.5, z), Vector3.new(7, 1, 4), RoofDark)
    end
    BuildMarketStall = function (name, pos)
      local x = pos.X
      local z = pos.Z

      -- Wooden counter
      SpawnBlock(name .. "_Counter", Vector3.new(x, 2, z), Vector3.new(6, 1, 3), TimberBrown)

      -- Support posts
      SpawnBlock(name .. "_Post1", Vector3.new(x - 2.5, 2.5, z + 1), Vector3.new(0.5, 5, 0.5), TimberBrown)
      SpawnBlock(name .. "_Post2", Vector3.new(x + 2.5, 2.5, z + 1), Vector3.new(0.5, 5, 0.5), TimberBrown)

      -- Canopy
      SpawnBlock(name .. "_Canopy", Vector3.new(x, 5.5, z), Vector3.new(7, 0.3, 5), Color3.fromRGB(180, 50, 50))
    end
    return {
      Setup = Setup,
      static = static
    }
  end)
end)

return true
