-- Generated by CSharp.lua Compiler
local System = _G.TestGame.System
return function (path)
  return System.init({
    root = script.Parent,
    path = path,
    files = {
      "GameScene",
      "Spawnable",
      "SpawnableBox"
    },
    types = {
      "TestGame.Spawnable",
      "TestGame.GameScene",
      "TestGame.SpawnableBox"
    },
    assembly = {
      Company = "TestGame",
      Configuration = "Debug",
      FileVersion = "1.0.0.0",
      InformationalVersion = "1.0.0+7ab5bb34b207cfacff0001ddb60dd8917249a6ee",
      Product = "TestGame",
      Title = "TestGame",
      Version = "1.0.0.0"
    }
  })
end
