-- Generated by CSharp.lua Compiler
local System = _G.TestGame.System
return function (path)
  return System.init({
    root = script.Parent,
    path = path,
    files = {
      "BuildingSpawner",
      "CurrencyManager",
      "GameScene",
      "ShopUI",
      "Spawnable",
      "SpawnableBox",
      "UIHelper"
    },
    types = {
      "TestGame.Spawnable",
      "TestGame.BuildingSpawner",
      "TestGame.CurrencyManager",
      "TestGame.GameScene",
      "TestGame.ShopItem",
      "TestGame.ShopUI",
      "TestGame.SpawnableBox",
      "TestGame.UIHelper"
    },
    assembly = {
      Company = "TestGame",
      Configuration = "Debug",
      FileVersion = "1.0.0.0",
      InformationalVersion = "1.0.0+7380943d37866b898a07cfd13f35ba1bea32e231",
      Product = "TestGame",
      Title = "TestGame",
      Version = "1.0.0.0"
    }
  })
end
