-- Generated by CSharp.lua Compiler
local System = _G.TestGame.System
local Roblox = _G.TestGame.Roblox
local DictStringTextButton = System.Dictionary(System.String, Roblox.TextButton)
local TestGame
local ListShopItem
System.import(function (out)
  TestGame = _G.TestGame.TestGame
  ListShopItem = System.List(TestGame.ShopItem)
end)
System.namespace("TestGame", function (namespace)
  -- <summary>
  -- Represents a purchasable item in the shop.
  -- </summary>
  namespace.class("ShopItem", function (namespace)
    local __ctor__
    __ctor__ = function (this, id, displayName, price, description, previewColor, spawnAction)
      this.PreviewColor = System.default(Roblox.Color3)
      this.Id = id
      this.DisplayName = displayName
      this.Price = price
      this.Description = description
      this.PreviewColor = previewColor
      this.SpawnAction = spawnAction
    end
    return {
      Price = 0,
      __ctor__ = __ctor__
    }
  end)

  -- <summary>
  -- Main shop UI controller. Creates and manages the building shop interface.
  -- </summary>
  namespace.class("ShopUI", function (namespace)
    local CreateShopItems, CreateShopPanel, CreateToggleButton, CreateCurrencyDisplay, CreateItemList, PopulateShopItems, ToggleShop, OnBuyClicked, 
    UpdateCurrencyDisplay, UpdateAllButtonStates, Initialize, class, __ctor__
    -- <summary>
    -- Creates the shop UI for a specific player.
    -- </summary>
    __ctor__ = function (this, player)
      this._buyButtons = DictStringTextButton()
      this._player = player
      this._currencyManager = TestGame.CurrencyManager(10000)
      this._shopItems = CreateShopItems(this)

      -- Create main ScreenGui
      this._screenGui = Instance.new("ScreenGui", player.PlayerGui)
      this._screenGui.Name = "BuildingShop"
      this._screenGui.IgnoreGuiInset = true
      this._screenGui.DisplayOrder = 10
      this._screenGui.ResetOnSpawn = false

      -- Create main shop panel (right side of screen)
      this._shopPanel = CreateShopPanel(this)

      -- Create toggle button
      this._toggleButton = CreateToggleButton(this)

      -- Create currency display
      this._coinLabel = CreateCurrencyDisplay(this)

      -- Create scrollable item list
      this._itemList = CreateItemList(this)

      -- Populate items
      PopulateShopItems(this)

      -- Subscribe to currency updates
      this._currencyManager.OnCoinsChanged = System.DelegateCombine(this._currencyManager.OnCoinsChanged, System.fn(this, UpdateCurrencyDisplay))
      this._currencyManager.OnCoinsChanged = System.DelegateCombine(this._currencyManager.OnCoinsChanged, System.fn(this, UpdateAllButtonStates))

      -- Start passive income
      this._currencyManager:StartPassiveIncome()

      System.Console.WriteLine("Shop UI initialized")
    end
    CreateShopItems = function (this)
      local default = ListShopItem()
      default:Add(TestGame.ShopItem("tree", "Tree", 100, "A simple tree", Color3.fromRGB(45, 95, 35), TestGame.BuildingSpawner.SpawnTree))
      default:Add(TestGame.ShopItem("well", "Well", 300, "Stone well with water", Color3.fromRGB(140, 135, 125), TestGame.BuildingSpawner.SpawnWell))
      default:Add(TestGame.ShopItem("small_house", "House (Small)", 500, "Cozy timber house", Color3.fromRGB(245, 235, 210), TestGame.BuildingSpawner.SpawnSmallHouse))
      default:Add(TestGame.ShopItem("market_stall", "Market Stall", 800, "Colorful vendor stall", Color3.fromRGB(180, 40, 45), TestGame.BuildingSpawner.SpawnMarketStall))
      default:Add(TestGame.ShopItem("large_house", "House (Large)", 1000, "Spacious family home", Color3.fromRGB(250, 245, 235), TestGame.BuildingSpawner.SpawnLargeHouse))
      default:Add(TestGame.ShopItem("tower", "Tower", 1500, "Tall stone watchtower", Color3.fromRGB(95, 90, 85), TestGame.BuildingSpawner.SpawnTower))
      default:Add(TestGame.ShopItem("windmill", "Windmill", 2500, "Working grain mill", Color3.fromRGB(180, 175, 165), TestGame.BuildingSpawner.SpawnWindmill))
      default:Add(TestGame.ShopItem("church", "Church", 3000, "Grand village church", Color3.fromRGB(180, 175, 165), TestGame.BuildingSpawner.SpawnChurch))
      return default
    end
    CreateShopPanel = function (this)
      local panel = TestGame.UIHelper.CreateMainPanel(this._screenGui, UDim2.new(0.25, 0, 0.8, 0), UDim2.new(0.74, 0, 0.1, 0))

      -- Header
      TestGame.UIHelper.CreateHeaderLabel(panel, "Building Shop")

      return panel
    end
    CreateToggleButton = function (this)
      local button = TestGame.UIHelper.CreateToggleButton(this._screenGui, UDim2.new(0, 50, 0, 50), UDim2.new(0.72, - 10, 0.1, 0))

      button.MouseButton1Click:Connect(System.fn(this, ToggleShop))

      return button
    end
    CreateCurrencyDisplay = function (this)
      local container, label = TestGame.UIHelper.CreateCoinDisplay(this._shopPanel, this._currencyManager:getCoins()):Deconstruct()
      return label
    end
    CreateItemList = function (this)
      return TestGame.UIHelper.CreateScrollFrame(this._shopPanel, UDim2.new(0.9, 0, 0.72, 0), UDim2.new(0.05, 0, 0, 115))
    end
    PopulateShopItems = function (this)
      local order = 0
      for _, item in System.each(this._shopItems) do
        local card, buyButton = TestGame.UIHelper.CreateShopItemCard(this._itemList, item.DisplayName, item.Description, item.Price, item.PreviewColor, order):Deconstruct()

        -- Store button reference for state updates
        this._buyButtons:set(item.Id, buyButton)

        -- Set initial button state
        TestGame.UIHelper.SetButtonEnabled(buyButton, this._currencyManager:CanAfford(item.Price))

        -- Connect buy action
        local capturedItem = item
        -- Capture for closure
        buyButton.MouseButton1Click:Connect(function ()
          OnBuyClicked(this, capturedItem)
        end)

        order = order + 1
      end
    end
    ToggleShop = function (this)
      this._isShopOpen = not this._isShopOpen
      this._shopPanel.Visible = this._isShopOpen

      if this._isShopOpen then
        this._toggleButton.Text = "X"
        this._toggleButton.Size = UDim2.new(0, 50, 0, 50)
      else
        this._toggleButton.Text = "Shop"
        this._toggleButton.Size = UDim2.new(0, 70, 0, 40)
      end
    end
    OnBuyClicked = function (this, item)
      if not this._currencyManager:CanAfford(item.Price) then
        System.Console.WriteLine("Cannot afford " .. item.DisplayName .. "!")
        return
      end

      if this._currencyManager:TrySpend(item.Price) then
        -- Get spawn position in front of player
        local spawnPos = TestGame.BuildingSpawner.GetSpawnPosition(this._player, 20)

        -- Spawn the building
        item.SpawnAction(spawnPos)

        System.Console.WriteLine("Purchased " .. item.DisplayName .. " for " .. item.Price .. " coins!")
      end
    end
    UpdateCurrencyDisplay = function (this, newAmount)
      this._coinLabel.Text = TestGame.UIHelper.FormatNumber(newAmount)
    end
    UpdateAllButtonStates = function (this, currentCoins)
      for _, item in System.each(this._shopItems) do
        local default, button = this._buyButtons:TryGetValue(item.Id, nil)
        if default then
          TestGame.UIHelper.SetButtonEnabled(button, currentCoins >= item.Price)
        end
      end
    end
    -- <summary>
    -- Initializes the shop UI for a player.
    -- Call this when a player joins the game.
    -- </summary>
    Initialize = function (player)
      class(player)
    end
    class = {
      _isShopOpen = true,
      Initialize = Initialize,
      __ctor__ = __ctor__
    }
    return class
  end)
end)

return true
