-- Generated by CSharp.lua Compiler
local System = _G.TestGame.System
local Roblox = _G.TestGame.Roblox
System.namespace("TestGame", function (namespace)
  -- <summary>
  -- A spawnable box (Part) with configurable size and color.
  -- </summary>
  namespace.class("SpawnableBox", function (namespace)
    local Spawn, __ctor__
    __ctor__ = function (this, name, position, size, color)
      this.Size = System.default(Roblox.Vector3)
      this.Color = System.default(Roblox.Color3)
      System.base(this).__ctor__(this, name, position)
      this.Size = size
      this.Color = color
    end
    Spawn = function (this)
      local part = Instance.new("Part")
      part.Name = this.Name
      part.Size = this.Size
      part.Position = this.Position
      part.Color = this.Color
      part.Anchored = true
      -- So it doesn't fall
      part.Parent = workspace

      System.Console.WriteLine("Spawned " .. this.Name .. " at " .. tostring(this.Position))

      return part
    end
    return {
      base = function (out)
        return {
          out.TestGame.Spawnable
        }
      end,
      Spawn = Spawn,
      __ctor__ = __ctor__
    }
  end)
end)

return true
