-- Generated by CSharp.lua Compiler
local System = _G.TestGame.System
local Roblox = _G.TestGame.Roblox
System.namespace("TestGame", function (namespace)
  -- <summary>
  -- Base class for anything that can be spawned at a location.
  -- </summary>
  namespace.class("Spawnable", function (namespace)
    local __ctor__
    __ctor__ = function (this, name, position)
      this.Position = System.default(Roblox.Vector3)
      this.Name = name
      this.Position = position
    end
    return {
      __ctor__ = __ctor__
    }
  end)
end)

return true
