-- Generated by CSharp.lua Compiler
local System = _G.TestGame.System
local Roblox = _G.TestGame.Roblox
local ValueTupleFrameTextLabel
local ValueTupleFrameTextButton
System.import(function (out)
  ValueTupleFrameTextLabel = System.ValueTuple(Roblox.Frame, Roblox.TextLabel)
  ValueTupleFrameTextButton = System.ValueTuple(Roblox.Frame, Roblox.TextButton)
end)
System.namespace("TestGame", function (namespace)
  -- <summary>
  -- Helper class for creating consistently styled UI elements.
  -- </summary>
  namespace.class("UIHelper", function (namespace)
    local PrimaryBg, SecondaryBg, AccentGreen, AccentHover, TextWhite, TextGray, GoldColor, DisabledBg, 
    DisabledText, BorderColor, CreatePanel, CreateMainPanel, CreateLabel, CreateHeaderLabel, CreateButton, CreateToggleButton, 
    CreateScrollFrame, CreateCoinDisplay, CreateShopItemCard, FormatNumber, SetButtonEnabled, static
    static = function (this)
      PrimaryBg = Color3.fromRGB(30, 30, 40)
      this.PrimaryBg = PrimaryBg
      SecondaryBg = Color3.fromRGB(45, 45, 60)
      this.SecondaryBg = SecondaryBg
      AccentGreen = Color3.fromRGB(100, 200, 100)
      this.AccentGreen = AccentGreen
      AccentHover = Color3.fromRGB(120, 220, 120)
      this.AccentHover = AccentHover
      TextWhite = Color3.fromRGB(255, 255, 255)
      this.TextWhite = TextWhite
      TextGray = Color3.fromRGB(180, 180, 190)
      this.TextGray = TextGray
      GoldColor = Color3.fromRGB(255, 215, 0)
      this.GoldColor = GoldColor
      DisabledBg = Color3.fromRGB(80, 80, 90)
      this.DisabledBg = DisabledBg
      DisabledText = Color3.fromRGB(120, 120, 130)
      this.DisabledText = DisabledText
      BorderColor = Color3.fromRGB(60, 60, 80)
      this.BorderColor = BorderColor
    end
    CreatePanel = function (parent, size, position)
      local frame = Instance.new("Frame", parent)
      frame.Size = size
      frame.Position = position
      frame.BackgroundColor3 = SecondaryBg
      frame.BorderSizePixel = 0

      local corner = Instance.new("UICorner", frame)
      corner.CornerRadius = UDim.new(0, 12)

      return frame
    end
    CreateMainPanel = function (parent, size, position)
      local frame = Instance.new("Frame", parent)
      frame.Name = "ShopPanel"
      frame.Size = size
      frame.Position = position
      frame.BackgroundColor3 = PrimaryBg
      frame.BackgroundTransparency = 0.05
      frame.BorderSizePixel = 0

      local corner = Instance.new("UICorner", frame)
      corner.CornerRadius = UDim.new(0, 16)

      local stroke = Instance.new("UIStroke", frame)
      stroke.Color = BorderColor
      stroke.Thickness = 2

      return frame
    end
    CreateLabel = function (parent, text, fontSize)
      local label = Instance.new("TextLabel", parent)
      label.Text = text
      label.TextColor3 = TextWhite
      label.TextSize = fontSize
      label.BackgroundTransparency = 1
      label.Size = UDim2.new(1, 0, 0, fontSize + 8)

      return label
    end
    CreateHeaderLabel = function (parent, text)
      local label = CreateLabel(parent, text, 24)
      label.Name = "Header"
      label.Size = UDim2.new(1, 0, 0, 50)
      label.Position = UDim2.new(0, 0, 0, 10)
      label.TextXAlignment = Enum.TextXAlignment.Center

      return label
    end
    CreateButton = function (parent, text, size)
      local button = Instance.new("TextButton", parent)
      button.Size = size
      button.Text = text
      button.TextColor3 = TextWhite
      button.BackgroundColor3 = AccentGreen
      button.TextSize = 16
      button.BorderSizePixel = 0
      button.AutoButtonColor = true

      local corner = Instance.new("UICorner", button)
      corner.CornerRadius = UDim.new(0, 8)

      return button
    end
    CreateToggleButton = function (parent, size, position)
      local button = Instance.new("TextButton", parent)
      button.Name = "ToggleShop"
      button.Size = size
      button.Position = position
      button.Text = "X"
      button.TextSize = 24
      button.BackgroundColor3 = PrimaryBg
      button.TextColor3 = TextWhite
      button.BorderSizePixel = 0
      button.AutoButtonColor = true

      local corner = Instance.new("UICorner", button)
      corner.CornerRadius = UDim.new(0, 8)

      local stroke = Instance.new("UIStroke", button)
      stroke.Color = BorderColor
      stroke.Thickness = 1

      return button
    end
    CreateScrollFrame = function (parent, size, position)
      local scroll = Instance.new("ScrollingFrame", parent)
      scroll.Name = "ItemList"
      scroll.Size = size
      scroll.Position = position
      scroll.BackgroundTransparency = 1
      scroll.BorderSizePixel = 0
      scroll.ScrollBarThickness = 6
      scroll.ScrollBarImageColor3 = TextGray
      scroll.AutomaticCanvasSize = Enum.AutomaticSize.Y
      scroll.CanvasSize = UDim2.new(0, 0, 0, 0)
      scroll.ScrollingDirection = Enum.ScrollingDirection.Y

      local layout = Instance.new("UIListLayout", scroll)
      layout.Padding = UDim.new(0, 10)
      layout.SortOrder = Enum.SortOrder.LayoutOrder
      layout.HorizontalAlignment = Enum.HorizontalAlignment.Center

      local padding = Instance.new("UIPadding", scroll)
      padding.PaddingTop = UDim.new(0, 5)
      padding.PaddingBottom = UDim.new(0, 5)

      return scroll
    end
    CreateCoinDisplay = function (parent, initialCoins)
      local coinFrame = Instance.new("Frame", parent)
      coinFrame.Name = "CoinDisplay"
      coinFrame.Size = UDim2.new(0.9, 0, 0, 40)
      coinFrame.Position = UDim2.new(0.05, 0, 0, 60)
      coinFrame.BackgroundColor3 = SecondaryBg
      coinFrame.BorderSizePixel = 0

      local corner = Instance.new("UICorner", coinFrame)
      corner.CornerRadius = UDim.new(0, 8)

      -- Coin icon (gold circle)
      local coinIcon = Instance.new("Frame", coinFrame)
      coinIcon.Name = "CoinIcon"
      coinIcon.Size = UDim2.new(0, 24, 0, 24)
      coinIcon.Position = UDim2.new(0, 10, 0.5, - 12)
      coinIcon.BackgroundColor3 = GoldColor
      coinIcon.BorderSizePixel = 0

      local iconCorner = Instance.new("UICorner", coinIcon)
      iconCorner.CornerRadius = UDim.new(0.5, 0)

      -- Coin amount label
      local coinLabel = Instance.new("TextLabel", coinFrame)
      coinLabel.Name = "CoinAmount"
      coinLabel.Size = UDim2.new(1, - 50, 1, 0)
      coinLabel.Position = UDim2.new(0, 45, 0, 0)
      coinLabel.BackgroundTransparency = 1
      coinLabel.Text = FormatNumber(initialCoins)
      coinLabel.TextColor3 = GoldColor
      coinLabel.TextSize = 20
      coinLabel.TextXAlignment = Enum.TextXAlignment.Left

      return ValueTupleFrameTextLabel(coinFrame, coinLabel)
    end
    CreateShopItemCard = function (parent, name, description, price, previewColor, layoutOrder)
      -- Main card container
      local card = Instance.new("Frame", parent)
      card.Name = "Item_" .. System.String.Replace(name, " ", "")
      card.Size = UDim2.new(1, - 20, 0, 90)
      card.BackgroundColor3 = SecondaryBg
      card.BorderSizePixel = 0
      card.LayoutOrder = layoutOrder

      local corner = Instance.new("UICorner", card)
      corner.CornerRadius = UDim.new(0, 8)

      local padding = Instance.new("UIPadding", card)
      padding.PaddingLeft = UDim.new(0, 10)
      padding.PaddingRight = UDim.new(0, 10)
      padding.PaddingTop = UDim.new(0, 10)
      padding.PaddingBottom = UDim.new(0, 10)

      -- Color preview box (left side)
      local preview = Instance.new("Frame", card)
      preview.Name = "Preview"
      preview.Size = UDim2.new(0, 50, 0, 50)
      preview.Position = UDim2.new(0, 0, 0.5, - 25)
      preview.BackgroundColor3 = previewColor
      preview.BorderSizePixel = 0

      local previewCorner = Instance.new("UICorner", preview)
      previewCorner.CornerRadius = UDim.new(0, 6)

      -- Item name
      local nameLabel = Instance.new("TextLabel", card)
      nameLabel.Name = "ItemName"
      nameLabel.Size = UDim2.new(0, 120, 0, 22)
      nameLabel.Position = UDim2.new(0, 65, 0, 5)
      nameLabel.BackgroundTransparency = 1
      nameLabel.Text = name
      nameLabel.TextColor3 = TextWhite
      nameLabel.TextSize = 16
      nameLabel.TextXAlignment = Enum.TextXAlignment.Left
      nameLabel.TextTruncate = Enum.TextTruncate.AtEnd

      -- Price label with coin indicator
      local priceLabel = Instance.new("TextLabel", card)
      priceLabel.Name = "Price"
      priceLabel.Size = UDim2.new(0, 100, 0, 18)
      priceLabel.Position = UDim2.new(0, 65, 0, 28)
      priceLabel.BackgroundTransparency = 1
      priceLabel.Text = FormatNumber(price) .. " coins"
      priceLabel.TextColor3 = GoldColor
      priceLabel.TextSize = 14
      priceLabel.TextXAlignment = Enum.TextXAlignment.Left

      -- Description
      local descLabel = Instance.new("TextLabel", card)
      descLabel.Name = "Description"
      descLabel.Size = UDim2.new(0, 120, 0, 16)
      descLabel.Position = UDim2.new(0, 65, 0, 48)
      descLabel.BackgroundTransparency = 1
      descLabel.Text = description
      descLabel.TextColor3 = TextGray
      descLabel.TextSize = 12
      descLabel.TextXAlignment = Enum.TextXAlignment.Left
      descLabel.TextTruncate = Enum.TextTruncate.AtEnd

      -- Buy button (right side)
      local buyButton = Instance.new("TextButton", card)
      buyButton.Name = "BuyButton"
      buyButton.Size = UDim2.new(0, 70, 0, 35)
      buyButton.Position = UDim2.new(1, - 70, 0.5, - 17)
      buyButton.Text = "BUY"
      buyButton.TextColor3 = TextWhite
      buyButton.BackgroundColor3 = AccentGreen
      buyButton.TextSize = 14
      buyButton.BorderSizePixel = 0
      buyButton.AutoButtonColor = true

      local buyCorner = Instance.new("UICorner", buyButton)
      buyCorner.CornerRadius = UDim.new(0, 6)

      return ValueTupleFrameTextButton(card, buyButton)
    end
    FormatNumber = function (number)
      if number >= 1000000 then
        return System.Double.ToString((number / 1000000.0), "0.#") .. "M"
      end
      if number >= 1000 then
        return System.Double.ToString((number / 1000.0), "0.#") .. "K"
      end
      return System.Int32.ToString(number)
    end
    SetButtonEnabled = function (button, enabled)
      button.BackgroundColor3 = enabled and AccentGreen or DisabledBg
      button.TextColor3 = enabled and TextWhite or DisabledText
      button.AutoButtonColor = enabled
    end
    return {
      CreatePanel = CreatePanel,
      CreateMainPanel = CreateMainPanel,
      CreateLabel = CreateLabel,
      CreateHeaderLabel = CreateHeaderLabel,
      CreateButton = CreateButton,
      CreateToggleButton = CreateToggleButton,
      CreateScrollFrame = CreateScrollFrame,
      CreateCoinDisplay = CreateCoinDisplay,
      CreateShopItemCard = CreateShopItemCard,
      FormatNumber = FormatNumber,
      SetButtonEnabled = SetButtonEnabled,
      static = static
    }
  end)
end)

return true
